Repository sillsdev/web-xforge, pull requests merged in 2022-08, with the labels that each got.

#1454 SF-1660 Allow re-marking node as invalid
  src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
  test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
Labels: testing complete

#1455 SF-1664 Reword project settings page
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#1460 SF-1657 Project is a source even when suggestions are disabled
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: testing complete

#1447 SF-1495 Retain attributes when undo inserts a blank
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
Labels: testing complete

#1457 SF-1624 Fix training indicator for RTL UI
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
Labels: testing complete

#1462 SF-1667 Fix stars on suggestion card for RTL UI
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
Labels: ready to test

#1456 SF-1654 Fix chapter dropdown for RTL UI
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
Labels: testing complete

#1464 SF-1673 Add user to source project even when suggestions disabled
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: testing complete

#1446 SF-1640 Add attributes on the paste operation
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
Labels: ready to test

#1450 SF-1656 Do not build machine project when target has no source books
  src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: ready to test

#1466 dev: update deps, vagrant
  deploy/dependencies.yml
  deploy/vagrant/sfdev/Vagrantfile
  deploy/vagrant/sfdev/base/provision
Labels: blocker

#1448 SF-1635 Open footnotes in dialog
  src/SIL.XForge.Scripture/ClientApp/src/_usx.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: ready to test

#1459 SF-1633 SF-1634 SF-1631 Fix direction of dialogs when UI is set to RTL
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts
Labels: ready to test

#1465 SF-1630 Fix Machine API 400 error when PT role changes
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: will require testing

#1458 SF-1677 Fix suggestions settings dialog for RTL UI
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.scss
Labels: testing complete

#1449 SF-1608 Improve quality of Bugsnag reporting
  src/SIL.XForge.Scripture/Controllers/ParatextController.cs
  src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
  src/SIL.XForge.Scripture/Controllers/SFProjectsUploadController.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge/Controllers/RpcControllerBase.cs
  src/SIL.XForge/Controllers/UsersRpcController.cs
  src/SIL.XForge/ExceptionLogging/ExceptionHandler.cs
  src/SIL.XForge/ExceptionLogging/ExceptionHandlerServiceCollectionExtensions.cs
  src/SIL.XForge/ExceptionLogging/IExceptionHandler.cs
  src/SIL.XForge/SIL.XForge.csproj
  test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsRpcControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: testing complete

#1473 SF-1681 Fix padding in community checking RTL UI
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
Labels: testing complete

#1472 SF-1627 Fix audio player in RTL mode
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.spec.ts
Labels: testing complete

#1471 SF-1680 Internationalize share control role
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html
Labels: testing complete

#1477 SF-1692 Fix order of books on translate overview page
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
Labels: testing complete

#1470 SF-1554 Enable Arabic localization in production
  src/SIL.XForge.Scripture/locales.json
Labels: testing complete

#1479 SF-1695 Fix footnote dialog when project or UI is RTL
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts
Labels: testing complete

#1475 SF-1691 Show indication in menu when sync has failed
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
Labels: testing complete

#1476 SF-1674 Inform user when lacking permission to edit chapter
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#1463 SF-1390 Users with a project role can join project via share link
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: testing complete

#1442 SF-1653 Update text anchor when multiple edits in a delta
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/segment.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing complete

#1480 SF-1700 Save inflight op to position 0 in IndexedDB
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts
Labels: ready to test

#1428 SF-1596 Enable passwordless login
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.guard.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.guard.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
Labels: ready to test
