Repository sillsdev/web-xforge, pull requests merged in 2022-12, with the labels that each got.

#1614 SF-1825 Add pseudo localization
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pseudo-localization.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pseudo-localization.ts
Labels: testing not required

#1624 Update package-lock.json in ClientApp
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
Labels: testing not required

#1623 SF-1826 Fix error calling getWordGraph
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
Labels: testing complete

#1628 Update decode-uri-component to fix vulnerability
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
Labels: testing not required

#1630 SF-1828 Fix generic dialog direction
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts
Labels: testing complete

#1613 Remove Ubuntu 22.04 build
  .github/workflows/build-and-test.yml
Labels: testing not required

#1633 Fix Code Coverage on .NET 7.0
  .github/workflows/build-and-test.yml
  test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
  test/SIL.XForge.Tests/SIL.XForge.Tests.csproj
Labels: testing not required

#1629 Update to Angular 14
  src/SIL.XForge.Scripture/ClientApp/angular.json
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/delete-project-dialog/delete-project-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/page-not-found/page-not-found.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/page-not-found/page-not-found.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfvalidators.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xfvalidators.spec.ts
  src/SIL.XForge.Scripture/ClientApp/tsconfig.json
Labels: testing complete

#1632 Update CSharpier to 0.21
  .config/dotnet-tools.json
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  test/SIL.XForge.Tests/Realtime/RichText/DeltaTests.cs
Labels: testing not required

#1631 Update ESLint packages
  src/RealtimeServer/package-lock.json
  src/RealtimeServer/package.json
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.ts
Labels: testing not required

#1634 SF-1831 Specify min height on ql editor
  src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.scss
Labels: ready to test

#1638 Update Jest from v27 to v29
  src/RealtimeServer/package-lock.json
  src/RealtimeServer/package.json
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
Labels: testing not required

#1637 Fix Angular warnings regarding CommonJS and AMD modules
  src/SIL.XForge.Scripture/ClientApp/angular.json
Labels: testing not required

#1589 doc: add section .NET performance profiling
  README.md
Labels: testing not required

#1612 Create codeql.yml to migrate from LGTM.com to GHA
  .github/codeql/codeql-javascript-config.yml
  .github/workflows/codeql.yml
Labels: testing not required

#1636 .NET Dependency Updates
  README.md
  deploy/dependencies.yml
  src/Help/UpdateHelp/UpdateHelp.csproj
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge/DataAccess/DataAccessApplicationBuilderExtensions.cs
  src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs
  src/SIL.XForge/DataAccess/MongoRepository.cs
  src/SIL.XForge/DataAccess/XFFieldDefinition.cs
  src/SIL.XForge/Realtime/RealtimeJsonService.cs
  src/SIL.XForge/SIL.XForge.csproj
  src/SIL.XForge/Services/EmailService.cs
  test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
  test/SIL.XForge.Scripture.Tests/Services/JwtInternetSharedRepositorySourceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MockScrText.cs
  test/SIL.XForge.Tests/SIL.XForge.Tests.csproj
  xForge.sln
Labels: testing not required

#1645 CodeQL fixes in Unit Tests
  test/SIL.XForge.Scripture.Tests/Services/InternetSharedRepositorySourceProviderTests.cs
  test/SIL.XForge.Scripture.Tests/Services/JwtInternetSharedRepositorySourceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MockCommentTags.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextNoteExtensions.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
  test/SIL.XForge.Tests/DataAccess/MemoryUpdateBuilderTests.cs
  test/SIL.XForge.Tests/Realtime/ConnectionTests.cs
  test/SIL.XForge.Tests/Realtime/RealtimeServiceTests.cs
  test/SIL.XForge.Tests/Services/ProjectServiceTests.cs
  test/SIL.XForge.Tests/Services/UserServiceTests.cs
Labels: testing not required

#1640 Update .editorconfig
  .editorconfig
Labels: testing not required

#1607 SF-1764 C# API for Machine API
  src/SIL.XForge.Scripture/Models/FeatureFlags.cs
  src/SIL.XForge.Scripture/Models/MachineApiCorpusFile.cs
  src/SIL.XForge.Scripture/Models/MachineApiTranslationEngine.cs
  src/SIL.XForge.Scripture/Models/MachineCorpus.cs
  src/SIL.XForge.Scripture/Models/MachineCorpusFile.cs
  src/SIL.XForge.Scripture/Models/MachineData.cs
  src/SIL.XForge.Scripture/Models/SFProjectSecret.cs
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/Services/IMachineBuildService.cs
  src/SIL.XForge.Scripture/Services/IMachineCorporaService.cs
  src/SIL.XForge.Scripture/Services/IMachineProjectService.cs
  src/SIL.XForge.Scripture/Services/IMachineTranslationService.cs
  src/SIL.XForge.Scripture/Services/MachineBuildService.cs
  src/SIL.XForge.Scripture/Services/MachineCorporaService.cs
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  src/SIL.XForge.Scripture/Services/MachineServiceBase.cs
  src/SIL.XForge.Scripture/Services/MachineServiceCollectionExtensions.cs
  src/SIL.XForge.Scripture/Services/MachineTranslationService.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge.Scripture/Startup.cs
  src/SIL.XForge.Scripture/appsettings.json
  src/SIL.XForge/Configuration/ConfigurationServiceCollectionExtensions.cs
  src/SIL.XForge/Configuration/MachineOptions.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineBuildServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineCorporaServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineTranslationServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MockExceptionHandler.cs
  test/SIL.XForge.Scripture.Tests/Services/MockHttpMessageHandler.cs
  test/SIL.XForge.Scripture.Tests/Services/MockText.cs
  test/SIL.XForge.Scripture.Tests/Services/MockTextCorpus.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SyncServiceTests.cs
Labels: testing complete

#1625 SF-1827 Add username for community checkers
  src/SIL.XForge.Scripture/Models/SFProjectRole.cs
  src/SIL.XForge.Scripture/Services/IParatextNotesMapper.cs
  src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge/Services/IUserService.cs
  src/SIL.XForge/Services/UserService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: ready to test

#1601 SF-1820 Suggestion incorrectly displays current word after inserting a suggestion
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.ts
Labels: testing complete

#1532 SF-1760 Allow auth0 account users to edit name while online
  src/RealtimeServer/common/models/user.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts
Labels: ready to test
