Repository sillsdev/web-xforge, pull requests merged in 2022-10, with the labels that each got.

#1523 SF-1762 Add basic RTL support to home pages
  src/SIL.XForge.Scripture/Pages/Privacy.cshtml
  src/SIL.XForge.Scripture/Pages/Shared/_Layout.cshtml
  src/SIL.XForge.Scripture/Pages/Terms.cshtml
  src/SIL.XForge.Scripture/wwwroot/css/sf.min.css
  src/SIL.XForge.Scripture/wwwroot/scss/_header.scss
  src/SIL.XForge.Scripture/wwwroot/scss/_home.scss
  src/SIL.XForge.Scripture/wwwroot/scss/_layout.scss
Labels: testing complete

#1528 SF-1748 Properly display verse refs in RTL script
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
Labels: ready to test

#1519 SF-1729 Ensure presence cursor is removed when going offline
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
Labels: testing complete

#1529 SF-1737 Yellow highlight does not appear for reference passages in the question dialog
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts
Labels: testing complete

#1533 SF-1699 Avoid deleting embeds when backspacing or deleting word
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
Labels: ready to test

#1522 SF-1727 Make presence avatars clickable and scroll to position in the document
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.ts
Labels: testing complete

#1535 SF-1542 - Unassigned text does not appear on note dialog after note update
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
  src/SIL.XForge.Scripture/Models/NoteThreadChange.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: testing complete

#1536 SF-1757 - Note icon does not disappear when resolved in PT
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing complete

#1543 SF-1770 Fix footer in RTL mode
  src/SIL.XForge.Scripture/wwwroot/css/sf.min.css
  src/SIL.XForge.Scripture/wwwroot/scss/_footer.scss
Labels: testing complete

#1552 Turn on TS option useUnknownInCatchVariables
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts
  src/SIL.XForge.Scripture/ClientApp/tsconfig.json
Labels: testing not required

#1551 Modify translate metrics query to output CSV
  mongodb/TranslateMetrics/TranslateMetricsAggregationByBook.mongodb
  mongodb/TranslateMetrics/TranslateMetricsAggregationByChapter.mongodb
Labels: testing not required

#1556 SF-1771 Add help links to footer
  src/SIL.XForge.Scripture/Pages/Shared/Components/Footer/Default.cshtml
  src/SIL.XForge.Scripture/Resources/SharedResource.resx
  src/SIL.XForge.Scripture/SharedResource.cs
  src/SIL.XForge.Scripture/wwwroot/css/sf.min.css
  src/SIL.XForge.Scripture/wwwroot/scss/_footer.scss
  src/SIL.XForge/Models/InterfaceLanguage.cs
Labels: testing complete

#1505 SF-1733 Redirect users viewing a deleted book
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: ready to test

#1558 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_zh_CN.json
  src/SIL.XForge.Scripture/Resources/SharedResource.ar.resx
  src/SIL.XForge.Scripture/Resources/SharedResource.az.resx
  src/SIL.XForge.Scripture/Resources/SharedResource.es.resx
  src/SIL.XForge.Scripture/Resources/SharedResource.fr.resx
  src/SIL.XForge.Scripture/Resources/SharedResource.id.resx
  src/SIL.XForge.Scripture/Resources/SharedResource.kyu.resx
  src/SIL.XForge.Scripture/Resources/SharedResource.lo.resx
  src/SIL.XForge.Scripture/Resources/SharedResource.pt-BR.resx
  src/SIL.XForge.Scripture/Resources/SharedResource.ro.resx
  src/SIL.XForge.Scripture/Resources/SharedResource.ru.resx
  src/SIL.XForge.Scripture/Resources/SharedResource.zh-CN.resx
Labels: testing not required

#1548 SF-1780 Update share link to material
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts
Labels: testing complete

#1563 SF-1788 Fix placement of nav component arrow icons
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
Labels: testing complete

#1521 SF-1743c sync: ensure correct revision is checked out when sync starts
  src/SIL.XForge.Scripture/Services/HgWrapper.cs
  src/SIL.XForge.Scripture/Services/IHgWrapper.cs
  src/SIL.XForge.Scripture/Services/IParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: testing complete

#1564 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
Labels: testing not required

#1565 dev: do not launch browser after compile
  src/SIL.XForge.Scripture/Properties/launchSettings.json
Labels: testing not required

#1559 dev: add attach to realtime server
  .vscode/launch.json
  README.md
  src/RealtimeServer/tsconfig.json
  src/SIL.XForge.Scripture/Realtime/SFRealtimeServiceCollectionExtensions.cs
  src/SIL.XForge.Scripture/Startup.cs
  src/SIL.XForge/Realtime/RealtimeServiceCollectionExtensions.cs
Labels: testing not required

#1555 Add query for texts with lots of edits
  mongodb/Texts/TextsWithLotsOfEdits.mongodb
Labels: testing not required

#1567 SF-1789 Skip non-PT users when querying unregistered project PT roles
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: testing complete

#1553 SF-1781 Add role description to role selector
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
Labels: testing complete

#1571 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json
  src/SIL.XForge.Scripture/Resources/SharedResource.ar.resx
Labels: testing not required

#1561 tool: enhance text-doc-history.js
  scripts/db_tools/text-doc-history.js
Labels: testing not required

#1572 Update socket.io-parser to 4.0.5 to fix potential vulnerability
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
Labels: testing not required
