Repository sillsdev/web-xforge, pull requests merged in 2022-09, with the labels that each got.

#1478 SF-1693 Fix question icons not showing up
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts
Labels: testing complete

#1484 SF-1587 SF-1580 SF-1611 Multi-cursor fixes to presence logic
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-realtime-remote-store.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-remote-store.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts
Labels: testing complete

#1481 SF-1663 Consolidate how note threads are embedded
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: ready to test

#1503 SF-1742 Fix drag and drop by fixing type guards
  src/SIL.XForge.Scripture/ClientApp/src/utils.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/utils.ts
Labels: fix recent change, blocker, testing complete

#1497 SF-1736 Confirm before removing user
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/generic-dialog/generic-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/generic-dialog/generic-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xforge-common.module.ts
Labels: testing complete

#1499 SF-1702 Improve support for other footnote callers
  src/SIL.XForge.Scripture/ClientApp/src/_text.scss
  src/SIL.XForge.Scripture/ClientApp/src/_usx.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
Labels: testing complete

#1469 SF-1678 Convert scripture view dialogs to angular material
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfvalidators.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts
Labels: testing complete

#1509 SF-1704b Show edit options only when feature enabled
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
Labels: fix recent change

#1508 SF-1751 Fix error opening ScriptureChooserDialogComponent
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
Labels: fix recent change, testing complete

#1506 SF-1610 Larger cursor appears when presence is on a blank heading
  src/SIL.XForge.Scripture/ClientApp/src/_usx.scss
Labels: testing complete

#1515 SF-1743a Stop sync if repo mismatch
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: will require testing

#1517 SF-1743b Revise test comments
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: no-testing-required

#1491 SF-1696 Fix connecting issue with Auth0 when loading PWA while offline
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-realtime-remote-store.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-remote-store.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts
Labels: testing complete

#1514 SF-1734 Display note thread icons when query is ready
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing complete

#1510 SF-1753 Replace message dialog with generic dialog
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/message-dialog/message-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/message-dialog/message-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xforge-common.module.ts
Labels: ready to test

#1485 SF-1614 Save the results of each sync to the database
  src/SIL.XForge.Scripture/DataAccess/SFDataAccessApplicationBuilderExtensions.cs
  src/SIL.XForge.Scripture/DataAccess/SFDataAccessServiceCollectionExtensions.cs
  src/SIL.XForge.Scripture/Models/NoteSyncMetricInfo.cs
  src/SIL.XForge.Scripture/Models/SFProjectSecret.cs
  src/SIL.XForge.Scripture/Models/SyncMetricInfo.cs
  src/SIL.XForge.Scripture/Models/SyncMetrics.cs
  src/SIL.XForge.Scripture/Models/SyncStatus.cs
  src/SIL.XForge.Scripture/Services/IParatextService.cs
  src/SIL.XForge.Scripture/Services/IParatextSyncRunner.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  src/SIL.XForge.Scripture/Services/SyncService.cs
  test/SIL.XForge.Scripture.Tests/Models/NoteSyncMetricInfoTests.cs
  test/SIL.XForge.Scripture.Tests/Models/SyncMetricInfoTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SyncServiceTests.cs
Labels: testing complete

#1518 SF-1750 SF-1017 Fix infinite loop when user doc updated
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user-projects.service.ts
Labels: ready to test
