Repository sillsdev/web-xforge, pull requests merged in 2022-11, with the labels that each got.

#1562 SF-1617 Allow importing question from TSV file
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/csv-service.service.ts
Labels: testing complete

#1573 Clarify source of NullReferenceException
  src/SIL.XForge.Scripture/Services/ParatextService.cs
Labels: testing not required

#1568 SF-1790 Fix direction of text in snackbar
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts
Labels: testing complete

#1576 SF-1556 Prevent excessive queries from the front end
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
Labels: testing not required

#1534 Use the to do comment tag icon for the project for new note threads
  src/RealtimeServer/scriptureforge/models/sf-project.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
  src/SIL.XForge.Scripture/Models/ParatextSettings.cs
  src/SIL.XForge.Scripture/Models/SFProject.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: testing not required

#1580 tool: add deleteDoc to TS API for scripts
  scripts/db_tools/utils.d.ts
Labels: testing not required

#1584 doc: fix token expiration comment
  src/SIL.XForge/Models/Tokens.cs
Labels: testing not required

#1588 doc: fix level of section linting and formatting
  README.md
Labels: testing not required

#1592 Bump loader-utils to 2.0.3 to fix vulnerablity
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
Labels: testing not required

#1596 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_zh_CN.json
Labels: testing not required

#1593 Replace deprecated trimLeft and trimRight with trimStart and trimEnd
  src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts
Labels: testing not required

#1577 SF-1805 Improve performance of questions query in app component
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
Labels: testing complete

#1578 SF-1816 Fix app component observable type and behavior
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
Labels: testing complete

#1594 dev: reduce nesting in app component ngOnInit
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
Labels: testing not required

#1602 SF-1809 Fix overflowing project name in project select in Firefox
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
Labels: testing complete

#1590 doc: update production build steps to use script
  README.md
Labels: testing not required

#1549 SF-1778 Add reviewer role for invitation and share links
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-role-info.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge/Services/ProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: testing not required

#1566 format: ignore angular cache files
  .prettierignore
  src/RealtimeServer/.prettierignore
  src/SIL.XForge.Scripture/ClientApp/.prettierignore
Labels: testing not required

#1581 tool: import-project: make it more plain if connecting
  scripts/db_tools/import-project.ts
  src/RealtimeServer/typings/sharedb/lib/client.d.ts
Labels: testing not required

#1574 SF-1782 Enable insert note FAB for reviewer users
  src/SIL.XForge.Scripture/ClientApp/src/_text.scss
  src/SIL.XForge.Scripture/ClientApp/src/_usx.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing not required

#1582 dev: clarify and adjust variable names
  src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/Services/ParatextService.cs
Labels: testing not required

#1586 log: provide more information when failing to refresh PT token
  src/SIL.XForge.Scripture/Services/ParatextService.cs
Labels: testing not required

#1587 doc: offline testing
  README.md
Labels: testing not required

#1615 SF-1822 Fix race condition for querying documents before share link has resolved
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
Labels: ready to test

#1550 SF-1701 Allow archiving and republishing questions in bulk
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#1595 SF-1730 ci: improve GHA frontend test output
  .github/workflows/build-and-test.yml
  .github/workflows/ci-lint-prettier.yml
  src/RealtimeServer/package.json
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/ClientApp/src/karma.conf.js
Labels: testing not required

#1583 tool: add ping-rts.ts to query the state of the realtime server
  scripts/db_tools/package-lock.json
  scripts/db_tools/package.json
  scripts/db_tools/ping-rts.ts
Labels: testing not required

#1621 Disable code coverage report to fix build
  .github/workflows/build-and-test.yml
Labels: testing not required

#1608 Update README to better reflect current status of MDC and Flex-Layout
  README.md
Labels: testing not required

#1610 Update jest-expect-message and remove @types/jest-expect-message
  src/RealtimeServer/common/utils/eq.spec.ts
  src/RealtimeServer/package-lock.json
  src/RealtimeServer/package.json
Labels: testing not required

#1618 Replace deprecated substr with substring
  src/RealtimeServer/common/models/user.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
Labels: testing not required

#1617 Fix catching of errors to be type safe
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/type-utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-reporting.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
Labels: testing not required

#1616 Add type safe I18nKey type
  src/SIL.XForge.Scripture/ClientApp/src/type-utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
Labels: testing not required

#1606 SF-1821 Confirm before deleting answers
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts
Labels: will require testing

#1622 SF-1791 Fix UpdateAvailableEvent deprecation in PWA service
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/retrying-request.service.ts
Labels: will require testing
