Repository sillsdev/web-xforge, pull requests merged in 2022-07, with the labels that each got.

#1437 SF-1641 Fix production build by building RealtimeServer before ClientApp
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
Labels: blocker

#1431 SF-1639 Delay machine engine training until after document transaction commit
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
Labels: blocker, testing complete

#1435 SF-1638 Sync based on text even when suggestions disabled
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge.Scripture/Services/SyncService.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SyncServiceTests.cs
Labels: blocker, testing complete

#1430 SF-1609 Improve Resource Sync Efficiency
  src/RealtimeServer/scriptureforge/models/sf-project.ts
  src/SIL.XForge.Scripture/Models/ParatextResource.cs
  src/SIL.XForge.Scripture/Models/ResourceConfig.cs
  src/SIL.XForge.Scripture/Models/SFProject.cs
  src/SIL.XForge.Scripture/Services/IParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: testing complete

#1439 SF-1636 Hide suggestion settings when suggestions disabled
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
Labels: ready to test

#1424 SF-1462 Correctly define segments after stanza break
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
  src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
  test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
Labels: testing complete
