Repository sillsdev/web-xforge, pull requests merged in 2023-11, with the labels that each got.

#2148 SF-2272 Prevent corrupting text when user deletes all verse text offline
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
Labels: ready to test

#2150 SF-2303 Fix crash when deleting a chapter with BT Notes
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
Labels: testing complete

#2154 SF-2305 Fix timing issues with checking questions list
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
Labels: bug, testing complete

#2147 SF-2249 Handle invalid url book in draft preview and editor pages
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: bug, ready to test

#2155 Fix checking UI for some screen widths
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
Labels: bug, testing not required

#2162 SF-2321 Update typescript and @types/node
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
Labels: dependencies, testing not required

#2156 SF-2313 Ability to enable MT drafting in System Administration
  src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.ts
  src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
  src/SIL.XForge.Scripture/Services/ISFProjectService.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: testing not required

#2093 SF-2243 Roles and Permissions dialog (plus PT users managing scripture audio)
  src/RealtimeServer/scriptureforge/models/sf-project-role.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-role-info.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/project-router.guard.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/users/users.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.ts
  src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge/Services/IProjectService.cs
  src/SIL.XForge/Services/ProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
  test/SIL.XForge.Tests/Services/ProjectServiceTests.cs
Labels: ready to test

#2164 SF-2325 Fix draft percent complete display
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/mock-pretranslation-machine-api.ts
Labels: bug, testing complete

#2163 SF-2324 Update angular-split to 15.0.0
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
Labels: testing complete

#2152 SF-2263 Notify users when chapter audio is missing
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-global-vars.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
Labels: ready to test

#2129 SF-2288 Allow Selection of books on Serval for pre-translation
  src/RealtimeServer/scriptureforge/models/sf-project-test-data.ts
  src/RealtimeServer/scriptureforge/models/translate-config.ts
  src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts
  src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts
  src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
  src/SIL.XForge.Scripture/Models/BuildConfig.cs
  src/SIL.XForge.Scripture/Models/DraftConfig.cs
  src/SIL.XForge.Scripture/Services/BuildConfigJsonConverter.cs
  src/SIL.XForge.Scripture/Services/IMachineApiService.cs
  src/SIL.XForge.Scripture/Services/IMachineProjectService.cs
  src/SIL.XForge.Scripture/Services/ISFTextCorpusFactory.cs
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  src/SIL.XForge.Scripture/Services/SFTextCorpusFactory.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/BuildConfigJsonConverterTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: testing complete

#2166 Record endpoint information in Bugnsag for Serval errors
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
Labels: testing not required

#2161 SF-2322 Display copyright banner for translations that request it
  src/RealtimeServer/scriptureforge/models/sf-project.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/Models/ParatextSettings.cs
  src/SIL.XForge.Scripture/Models/SFProject.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: testing complete

#2130 SF-2291 Add queue depth visibility to Pre-Translation drafting
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/build-dto.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/mock-pretranslation-machine-api.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
  src/SIL.XForge.Scripture/Models/ServalBuildDto.cs
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/Services/IMachineApiService.cs
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiV2ControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
Labels: testing complete

#2172 SF-2330 Uploading valid timing data shows invalid state
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts
Labels: testing complete

#2169 SF-2323 - Various scripture audio player fixes
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player/audio-player.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player/audio-player.component.ts
Labels: testing complete

#2174 SF-2336 Update angular-file to 4.0.2
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
Labels: ready to test

#2165 SF-2297 Allow editing of scripture audio data
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
Labels: testing complete

#2153 SF-2307 SF-2308 Fix scripture audio play button and RTL skip buttons
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.scss
Labels: testing complete

#2159 SF-2317 Improve comment FAB position to not cover text
  src/SIL.XForge.Scripture/ClientApp/src/_text.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: ready to test

#2180 Update TypeScript to 4.9.5 in realtime server
  src/RealtimeServer/package-lock.json
  src/RealtimeServer/package.json
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
Labels: testing not required

#2177 Make audio icons in checking area more consistent
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
Labels: testing not required

#2178 Fix direction in splitter when in RTL mode
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: fix recent change, will require testing

#2160 SF-2269 Add sign-up link for pre-translation project approval
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/pretranslation-signup-url.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/pretranslation-signup-url.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: new feature, testing complete

#2184 SF-2348 Mirror question mark in RTL contexts
  src/SIL.XForge.Scripture/ClientApp/src/_text.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/info/info.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/info/info.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/info/info.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
Labels: testing complete

#2187 Improve translation drafting signup message
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#2181 SF-2344 Adjust pre-translation book selection
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/shared.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
Labels: testing complete

#2170 Update CSharpier to 0.26.3
  .config/dotnet-tools.json
  src/Migrations/BackoutCommits/Program.cs
  src/Migrations/BackoutCommits/Startup.cs
  src/Migrations/BackoutCommits/SyncAllService.cs
  src/Migrations/PTDDCloneAll.Tests/CloneAllServiceTests.cs
  src/Migrations/PTDDCloneAll/CloneAllService.cs
  src/Migrations/PTDDCloneAll/PTDDSyncRunner.cs
  src/Migrations/PTDDCloneAll/Program.cs
  src/Migrations/PTDDCloneAll/Startup.cs
  src/Migrations/PtdaSyncAll.Tests/PtdaSyncRunnerTests.cs
  src/Migrations/PtdaSyncAll.Tests/SyncAllServiceTests.cs
  src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs
  src/Migrations/PtdaSyncAll/Startup.cs
  src/Migrations/PtdaSyncAll/SyncAllService.cs
  src/Migrations/ServalMigration/ServalMigrator.cs
  src/Migrations/SourceTargetSplitting/ObjectMigrator.cs
  src/Migrations/SourceTargetSplitting/Startup.cs
  src/Migrations/SyncCancel/Startup.cs
  src/Migrations/SyncUserToPTUser/Startup.cs
  src/SIL.XForge.Scripture/Controllers/AnonymousController.cs
  src/SIL.XForge.Scripture/Controllers/LanguageController.cs
  src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  src/SIL.XForge.Scripture/Services/MachineServiceCollectionExtensions.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  src/SIL.XForge.Scripture/Services/SFBiblicalTermsText.cs
  src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge/Services/AuthServiceCollectionExtensions.cs
  src/SIL.XForge/Services/ProjectService.cs
  src/SIL.XForge/Services/UserService.cs
  test/SIL.XForge.Scripture.Tests/Services/InternetSharedRepositorySourceProviderTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/TransceleratorServiceTests.cs
  test/SIL.XForge.Tests/Realtime/ConnectionTests.cs
  test/SIL.XForge.Tests/Realtime/RealtimeServiceTests.cs
  test/SIL.XForge.Tests/Services/ProjectServiceTests.cs
  test/SIL.XForge.Tests/Services/UserServiceTests.cs
Labels: .NET, testing not required

#2158 SF-2311 Allow playing chapter audio immediately after upload
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
Labels: ready to test

#2171 SF-2332 Improve verse segment alignment for MT Drafting
  src/SIL.XForge.Scripture/Services/PreTranslationService.cs
  test/SIL.XForge.Scripture.Tests/Services/PreTranslationServiceTests.cs
Labels: testing complete

#2195 SF-2350 Fix draft generation progress circle rerender on click
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
Labels: ready to test

#2190 SF-2349 Align all projects to the left in project picker
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation-project-selector/navigation-project-selector.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation-project-selector/navigation-project-selector.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
Labels: ready to test

#2173 SF-2268 Custom Configuration for MT Drafting
  src/RealtimeServer/scriptureforge/models/translate-config.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-settings.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
  src/SIL.XForge.Scripture/Models/DraftConfig.cs
  src/SIL.XForge.Scripture/Services/ISFProjectService.cs
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsRpcControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: testing complete

#2193 Add Mongo query to count edits of most edited docs in each collection
  mongodb/count_document_revisions.mongodb
Labels: testing not required

#2198 Fix description of admin page drafting setting
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/system-administration.component.scss
Labels: testing not required

#2197 Fix project picker height
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation-project-selector/navigation-project-selector.component.scss
Labels: testing not required

#2196 Remove tooltip from question list
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
Labels: testing not required

#2192 Update drafting message to suggest one book at a time
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#2182 SF-2314 Allow opening roles & permissions dialog offline
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete
