Repository sillsdev/web-xforge, pull requests merged in 2023-03, with the labels that each got.

#1723 Help: Ignore auxiliary files during localization
  src/Help/UpdateHelp/Program.cs
Labels: testing not required

#1722 Migration fixes and clean ups
  src/RealtimeServer/common/realtime-server.spec.ts
  src/RealtimeServer/common/realtime-server.ts
  src/RealtimeServer/scriptureforge/services/note-thread-migrations.spec.ts
  src/RealtimeServer/scriptureforge/services/note-thread-migrations.ts
  src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts
Labels: bug, testing not required

#1726 Add Mongo query to count users by role
  mongodb/Projects/CountUserRoles.mongodb
Labels: testing not required

#1716 Memory and Speed Optimizations to the Sync Process
  src/RealtimeServer/common/index.ts
  src/SIL.XForge.Scripture/Services/IParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  src/SIL.XForge/Realtime/Connection.cs
  src/SIL.XForge/Realtime/Document.cs
  src/SIL.XForge/Realtime/IConnection.cs
  src/SIL.XForge/Realtime/IRealtimeServer.cs
  src/SIL.XForge/Realtime/MemoryConnection.cs
  src/SIL.XForge/Realtime/RealtimeServer.cs
  src/SIL.XForge/Realtime/Snapshot.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
  test/SIL.XForge.Tests/Realtime/ConnectionTests.cs
Labels: .NET, testing not required

#1735 SF-1906 Separate migration into distinct subprocess
  src/RealtimeServer/common/index.ts
  src/RealtimeServer/common/realtime-server.ts
  src/RealtimeServer/scriptureforge/migrator.ts
  src/RealtimeServer/scriptureforge/realtime-server.ts
  src/RealtimeServer/scriptureforge/tsconfig.build-esm.json
  src/SIL.XForge.Scripture/Migrator.cs
  src/SIL.XForge.Scripture/Program.cs
Labels: testing complete

#1738 dev: add target to debug ts-node script
  .vscode/launch.json
Labels: testing not required

#1737 tool: improve show-projects.ts
  scripts/db_tools/show-projects.ts
Labels: testing not required

#1728 SF-1892 Remove displayName from ProjectRoleInfo
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-role-info.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/project-role-info.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.ts
Labels: testing complete

#1733 SF-1891 Do not select a verse when clicking note thread icon
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing complete

#1741 Improve logging in the RealtimeJsonService
  src/SIL.XForge/Realtime/MemoryExceptionHandler.cs
  src/SIL.XForge/Realtime/MemoryRealtimeService.cs
  src/SIL.XForge/Realtime/RealtimeJsonService.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineBuildServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineCorporaServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineTranslationServiceTests.cs
Labels: testing not required

#1736 SF-1900 Delete comments in a deleted note thread
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
  src/SIL.XForge.Scripture/Models/Note.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: ready to test

#1732 SF-1889 Attribute new SF notes to reviewer user on sync
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: testing complete

#1724 SF-1798 Switch off drag and drop
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
Labels: testing complete

#1745 tool: clean up older vagrant pieces
  deploy/vagrant/sfdev/base/sfdev.json
  deploy/vagrant_xenial_gui/Vagrantfile
  deploy/virtualbox_xenial_gui_creation/Vagrantfile
  deploy/virtualbox_xenial_gui_creation/instructions.md
  deploy/virtualbox_xenial_gui_creation/xforge-u1604.json
Labels: testing not required

#1750 Fix migrator reading appsettings in production
  src/RealtimeServer/scriptureforge/migrator.ts
Labels: testing not required

#1751 Add noteTagId to CheckingConfig TS model
  src/RealtimeServer/scriptureforge/models/checking-config.ts
Labels: testing not required

#1748 SF-1883 Consider combined verse segments when opening note dialog
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
Labels: testing complete

#1753 SF-1919 - Hide option to "Show changes" when viewing a note if there are no changes
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
Labels: testing complete

#1754 SF-1918 - Add label to adding note textarea
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#1760 SF-1927 Allow all users to update their display name
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
Labels: ready to test

#1758 Configure ESLint to ignore unused variables that start with underscore
  src/RealtimeServer/.eslintrc.json
  src/SIL.XForge.Scripture/ClientApp/.eslintrc.json
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
Labels: testing not required

#1755 SF-1914 - Remove new note from toolbar and show FAB to admin
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing complete

#1759 SF-1765 Sync notes back to Paratext
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: testing not required

#1762 Simplify styling of notice component
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.scss
Labels: testing not required

#1747 SF-1908 Fix order of comments that were added in Paratext
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
Labels: ready to test

#1742 SF-1905 Disable adding a note on unavailable text
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#1763 SF-1930 Replace share icon with add user icon
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-button.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-button.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-button.component.ts
Labels: testing complete

#1766 Remove obsolete CheckUserNeedsMigrating endpoint
  src/SIL.XForge/Controllers/UsersRpcController.cs
Labels: testing not required

#1557 SF-1628 Fix src and seq not being correct after reconnection
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/typings/sharedb.d.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-realtime-remote-store.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/project-data-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-remote-store.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
Labels: will require testing

#1761 Improve ChildViewContainerComponent reuse
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-confirmation-dialog/import-questions-confirmation-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/delete-project-dialog/delete-project-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-utils.ts
Labels: testing not required

#1719 SF-1878b Highlight note thread only if unread notes exist
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
Labels: ready to test

#1770 SF-1464 Fix wrapping in user list
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
Labels: testing complete
