Repository sillsdev/web-xforge, pull requests merged in 2023-08, with the labels that each got.

#1984 SF-2141 Do not show an offline error when pasting a sharing link twice
  src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.ts
Labels: testing complete

#1973 SF-2158 Support for uploading large audio files
  src/SIL.XForge.Scripture/Controllers/SFProjectsUploadController.cs
  src/SIL.XForge/Services/AudioService.cs
  src/SIL.XForge/Services/IAudioService.cs
  src/SIL.XForge/Services/IProjectService.cs
  src/SIL.XForge/Services/ProjectService.cs
  test/SIL.XForge.Tests/Services/AudioServiceTests.cs
  test/SIL.XForge.Tests/Services/ProjectServiceTests.cs
Labels: testing complete

#1994 SF-2115 No projects connected page to material
  src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.scss
Labels: testing not required

#1993 SF-2147 Fix notes deleted in PT not deleted in SF
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: ready to test

#1997 SF-2170 Echo Support for Pre-Translation Drafting
  src/SIL.XForge.Scripture/Models/FeatureFlags.cs
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
Labels: testing not required

#2000 SF-2186 Skip syncing notes with invalid content to prevent sync failure
  src/SIL.XForge.Scripture/Services/ParatextService.cs
Labels: testing not required

#1988 SF-2173 Restrict note updating in Scripture Forge
  src/RealtimeServer/scriptureforge/models/note.ts
  src/RealtimeServer/scriptureforge/services/note-thread-service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/Models/FeatureFlags.cs
  src/SIL.XForge.Scripture/Models/Note.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: ready to test

#2004 SF-2053b Fix Build State case during Serval upload
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
Labels: testing not required

#1990 dev: vagrant: Add Chromium MP3 Support
  deploy/vagrant/sfdev/Vagrantfile
Labels: testing not required

#1985 SF-2026 Chapter Audio UI
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog-service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/info/info.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/info/info.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/info/info.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-utils.ts
  src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
  src/SIL.XForge.Scripture/Models/AudioTiming.cs
  src/SIL.XForge.Scripture/Services/ISFProjectService.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
Labels: ready to test

#1987 SF 2072 Replace MDC buttons with Material in checking component
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
Labels: testing complete

#1992 SF-2027 Update checking overview to display chapters with scripture audio
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: ready to test

#1998 SF-2179 Refreshing scripture audio when timing data changes
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts
Labels: testing not required

#1986 SF-2143 Adjust 503 error page wording
  src/SIL.XForge.Scripture/ErrorPages/503.html
Labels: testing not required

#2005 SF-2072b Fix nav buttons in checking component
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
Labels: fix recent change, Critical Path, testing not required

#2007 SF-2190 Add explicit return types
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-button.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/main.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/donut-chart/donut-chart.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/generic-dialog/generic-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/mock-console.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/route.directive.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/scroll-into-view.ts
Labels: will require testing

#1889 SF-2117 Theme more Material components
  .github/workflows/chromatic.yml
  src/SIL.XForge.Scripture/ClientApp/angular.json
  src/SIL.XForge.Scripture/ClientApp/src/_variables.scss
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/styles.scss
Labels: testing complete

#2008 SF-1910 Docker Support
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/tasks.json
  src/.dockerignore
  src/Docker/Docker.dcproj
  src/Docker/docker-compose.override.yml
  src/Docker/docker-compose.win.yml
  src/Docker/docker-compose.yml
  src/Docker/launchSettings.json
  src/RealtimeServer/scriptureforge/migrator.ts
  src/SIL.XForge.Scripture/Dockerfile
  src/SIL.XForge.Scripture/Program.cs
  src/SIL.XForge.Scripture/Properties/launchSettings.json
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  xForge.sln
Labels: testing not required

#2010 SF-2185 Fix error when user creates notes with invalid xml symbols
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
Labels: ready to test

#2016 SF-2196 Chapter Audio Matches Original Design
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player/audio-player.component.scss
Labels: testing not required

#2019 SF-2207 Leave breadcrumbs only if Bugsnag has started
  src/RealtimeServer/package-lock.json
  src/RealtimeServer/package.json
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bugsnag.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-reporting.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
Labels: testing not required

#1963 SF-2148 Migrators can use an existing NodeJS process
  src/Migrations/ServalMigration/Program.cs
  src/Migrations/ServalMigration/ServalMigrator.cs
  src/Migrations/ServalMigration/Startup.cs
  src/SIL.XForge.Scripture/Realtime/SFRealtimeServiceCollectionExtensions.cs
  src/SIL.XForge/Configuration/RealtimeOptions.cs
  src/SIL.XForge/Realtime/ExistingNodeJSProcess.cs
  src/SIL.XForge/Realtime/ExistingNodeJSProcessFactory.cs
  src/SIL.XForge/Realtime/RealtimeService.cs
  src/SIL.XForge/Realtime/RealtimeServiceCollectionExtensions.cs
Labels: ready to test

#1746 SF-1911 Data Validation in ShareDB and MongoDB
  scripts/db_tools/package-lock.json
  scripts/db_tools/package.json
  scripts/db_tools/validate-data.ts
  src/RealtimeServer/.eslintrc.json
  src/RealtimeServer/common/index.ts
  src/RealtimeServer/common/models/validation-schema.ts
  src/RealtimeServer/common/realtime-server.spec.ts
  src/RealtimeServer/common/realtime-server.ts
  src/RealtimeServer/common/services/doc-service.ts
  src/RealtimeServer/common/services/project-data-service.spec.ts
  src/RealtimeServer/common/services/project-data-service.ts
  src/RealtimeServer/common/services/project-service.spec.ts
  src/RealtimeServer/common/services/project-service.ts
  src/RealtimeServer/common/services/user-service.spec.ts
  src/RealtimeServer/common/services/user-service.ts
  src/RealtimeServer/package-lock.json
  src/RealtimeServer/package.json
  src/RealtimeServer/scriptureforge/migrator.ts
  src/RealtimeServer/scriptureforge/realtime-server.ts
  src/RealtimeServer/scriptureforge/services/note-thread-migrations.spec.ts
  src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts
  src/RealtimeServer/scriptureforge/services/note-thread-service.ts
  src/RealtimeServer/scriptureforge/services/question-migrations.spec.ts
  src/RealtimeServer/scriptureforge/services/question-service.spec.ts
  src/RealtimeServer/scriptureforge/services/question-service.ts
  src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.spec.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.ts
  src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.spec.ts
  src/RealtimeServer/scriptureforge/services/sf-project-user-config-service.ts
  src/RealtimeServer/scriptureforge/services/text-audio-service.spec.ts
  src/RealtimeServer/scriptureforge/services/text-audio-service.ts
  src/RealtimeServer/scriptureforge/services/text-service.spec.ts
  src/RealtimeServer/scriptureforge/services/text-service.ts
  src/RealtimeServer/typings/sharedb/lib/client.d.ts
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge/Configuration/RealtimeOptions.cs
  src/SIL.XForge/Realtime/RealtimeService.cs
Labels: ready to test

#2011 SF-2192 Optimize note thread query and display
  src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
Labels: ready to test

#2024 dev: Specify default solution for dotnet
  .vscode/settings.json
Labels: testing not required

#2025 SF-2214 Update SyncMetrics on Note Thread Deletion
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: testing not required

#1999 SF-2130 Integrate AudioPlayer into Existing Components
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player-new.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player-base/audio-player-base.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player/audio-player.component.html
Labels: testing complete

#2017 SF-2205 Remove mdc-typography class from body element
  src/SIL.XForge.Scripture/ClientApp/.storybook/preview.ts
  src/SIL.XForge.Scripture/ClientApp/src/index.html
  src/SIL.XForge.Scripture/ClientApp/src/styles.scss
Labels: testing complete

#2003 SF-2024 Highlight current audio text
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player-base/audio-player-base.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts
Labels: ready to test

#2031 SF-2222 Fix verse too long message by updating Machine.js
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
Labels: testing not required

#1961 SF-2045 Back translation draft UI
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/ClientApp/src/_text.scss
  src/SIL.XForge.Scripture/ClientApp/src/_variables.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/shared.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/working-animated-indicator/working-animated-indicator.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/working-animated-indicator/working-animated-indicator.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/working-animated-indicator/working-animated-indicator.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/working-animated-indicator/working-animated-indicator.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/mock-pretranslation-machine-api.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-languages.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-routing.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/activated-project.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/generic-dialog/generic-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/util/rxjs-util.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/util/rxjs-util.ts
Labels: new feature, will require testing
