Repository sillsdev/web-xforge, pull requests merged in 2023-07, with the labels that each got.

#1887 SF-2053 Backend Support for NMT Pre-Translation
  src/RealtimeServer/scriptureforge/models/translate-config.ts
  src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts
  src/RealtimeServer/scriptureforge/services/question-service.spec.ts
  src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts
  src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.spec.ts
  src/RealtimeServer/scriptureforge/services/text-audio-service.spec.ts
  src/RealtimeServer/scriptureforge/services/text-service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/build-states.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
  src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
  src/SIL.XForge.Scripture/Controllers/MachineApiV2Controller.cs
  src/SIL.XForge.Scripture/Models/MachineApi.cs
  src/SIL.XForge.Scripture/Models/PreTranslation.cs
  src/SIL.XForge.Scripture/Models/PreTranslationDto.cs
  src/SIL.XForge.Scripture/Models/ServalCorpus.cs
  src/SIL.XForge.Scripture/Models/ServalData.cs
  src/SIL.XForge.Scripture/Models/TranslateConfig.cs
  src/SIL.XForge.Scripture/Services/IMachineApiService.cs
  src/SIL.XForge.Scripture/Services/IMachineProjectService.cs
  src/SIL.XForge.Scripture/Services/IPreTranslationService.cs
  src/SIL.XForge.Scripture/Services/ISFTextCorpusFactory.cs
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  src/SIL.XForge.Scripture/Services/MachineServiceCollectionExtensions.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  src/SIL.XForge.Scripture/Services/PreTranslationService.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge.Scripture/Services/SFScriptureText.cs
  src/SIL.XForge.Scripture/Services/SFTextCorpusFactory.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiV2ControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/PreTranslationServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ServalApiExceptions.cs
Labels: testing not required

#1951 Skip pushing notes to PT
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: testing not required

#1941 SF-2114 Translate Overview to Material
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
Labels: testing complete

#1915 SF-2098 Suggestions Settings to Material
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
Labels: testing complete

#1908 dev: vagrant: rm mongodb 4.0
  deploy/vagrant/sfdev/Vagrantfile
Labels: testing not required

#1949 SF-2123 Allow incorrectly or partially deleted users to be removed from projects
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge/Services/ProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
  test/SIL.XForge.Tests/Services/ProjectServiceTests.cs
Labels: testing complete

#1945 SF-2125 Add stream checking for incoming MP3 data
  src/SIL.XForge.Scripture/Controllers/SFProjectsUploadController.cs
  src/SIL.XForge/Services/AudioService.cs
  src/SIL.XForge/Services/IAudioService.cs
  src/SIL.XForge/Services/ProjectService.cs
  test/SIL.XForge.Tests/Services/AudioServiceTests.cs
  test/SIL.XForge.Tests/Services/ProjectServiceTests.cs
Labels: testing complete

#1950 SF-2133 Fixed Alignment for Reviewer Questions Panel
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss
Labels: testing complete

#1934 Refactor audio playing to AudioPlayer
  src/SIL.XForge.Scripture/ClientApp/.storybook/main.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts
Labels: testing not required

#1946 SF-2129 Add Health Endpoint
  src/SIL.XForge.Scripture/Controllers/HealthController.cs
  src/SIL.XForge.Scripture/Models/HealthCheckComponent.cs
  src/SIL.XForge.Scripture/Models/HealthCheckResponse.cs
  test/SIL.XForge.Scripture.Tests/Controllers/HealthCheckControllerTests.cs
Labels: testing not required

#1943 SF-2128 Add ProjectType & BaseProject to TranslateConfig
  src/RealtimeServer/scriptureforge/models/translate-config.ts
  src/SIL.XForge.Scripture/Models/BaseProject.cs
  src/SIL.XForge.Scripture/Models/ParatextSettings.cs
  src/SIL.XForge.Scripture/Models/TranslateConfig.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: testing not required

#1956 Add TODO comments for scripture audio
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts
Labels: testing not required

#1942 Use `@sillsdev/scripture`
  mongodb/TranslateMetrics/TranslateMetricsAggregationByBook.mongodb
  mongodb/TranslateMetrics/TranslateMetricsAggregationByChapter.mongodb
  scripts/db_tools/find-problem-cids.ts
  scripts/db_tools/package-lock.json
  scripts/db_tools/package.json
  scripts/db_tools/show-projects.ts
  src/RealtimeServer/package-lock.json
  src/RealtimeServer/package.json
  src/RealtimeServer/scriptureforge/models/text-data.ts
  src/RealtimeServer/scriptureforge/models/verse-ref-data.ts
  src/RealtimeServer/scriptureforge/scripture-utils/book-set.ts
  src/RealtimeServer/scriptureforge/scripture-utils/canon.ts
  src/RealtimeServer/scriptureforge/scripture-utils/scr-vers.ts
  src/RealtimeServer/scriptureforge/scripture-utils/verse-ref.ts
  src/RealtimeServer/scriptureforge/scripture-utils/versification.ts
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfvalidators.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
Labels: testing complete

#1947 test: create test data from single source for SFProject, User
  .vscode/launch.json
  src/RealtimeServer/common/models/user-test-data.ts
  src/RealtimeServer/common/realtime-server.spec.ts
  src/RealtimeServer/common/services/project-data-service.spec.ts
  src/RealtimeServer/common/services/project-service.spec.ts
  src/RealtimeServer/common/services/user-service.spec.ts
  src/RealtimeServer/common/utils/type-utils.ts
  src/RealtimeServer/package-lock.json
  src/RealtimeServer/package.json
  src/RealtimeServer/scriptureforge/models/sf-project-test-data.ts
  src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts
  src/RealtimeServer/scriptureforge/services/question-service.spec.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.spec.ts
  src/RealtimeServer/scriptureforge/services/text-audio-service.spec.ts
  src/RealtimeServer/scriptureforge/services/text-service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/owner/owner.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.spec.ts
  src/SIL.XForge.Scripture/Models/TranslateSource.cs
Labels: testing not required

#1820 SF-2124 Rewrite NotesFormatter.ParseParagraph to use XElement
  src/SIL.XForge.Scripture/Services/NotesFormatter.cs
Labels: ready to test

#1962 Exclude Test Projects from Code Coverage Calculations
  test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
  test/SIL.XForge.Tests/SIL.XForge.Tests.csproj
Labels: testing not required

#1969 SF-2149 Make like color lighter
  src/SIL.XForge.Scripture/ClientApp/src/_variables.scss
Labels: testing not required

#1968 SF-1015 Add link to open source license page
  src/SIL.XForge.Scripture/ClientApp/angular.json
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/Startup.cs
Labels: testing complete

#1970 SF-2151 Retrieve the latest pre-translation build when finished
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
Labels: testing not required

#1974 .NET Dependency Updates
  src/Help/UpdateHelp/UpdateHelp.csproj
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge/SIL.XForge.csproj
  test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
  test/SIL.XForge.Tests/SIL.XForge.Tests.csproj
Labels: testing not required

#1971 SF-2152 Update to @sillsdev/scripture 1.4.0
  scripts/db_tools/package-lock.json
  scripts/db_tools/package.json
  src/RealtimeServer/package-lock.json
  src/RealtimeServer/package.json
  src/RealtimeServer/scriptureforge/models/verse-ref-data.ts
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
Labels: ready to test

#1975 SF-2159 Added GetLastCompletedPreTranslationBuild
  src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
  src/SIL.XForge.Scripture/Models/MachineApi.cs
  src/SIL.XForge.Scripture/Services/IMachineApiService.cs
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ServalApiExceptions.cs
Labels: testing not required

#1958 SF-2137 Add notes on threads with the correct thread Id
  src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
Labels: ready to test

#1960 SF-2146 Write Comment XML Files with the BOM
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge/Services/FileSystemService.cs
  src/SIL.XForge/Services/IFileSystemService.cs
  test/SIL.XForge.Tests/SIL.XForge.Tests.csproj
  test/SIL.XForge.Tests/Services/FileSystemServiceTests.cs
Labels: ready to test

#1964 SF-2025 Question plays audio and relevant scripture audio.
  src/SIL.XForge.Scripture/ClientApp/src/app/checking-question/checking-question.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking-question/checking-question.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking-question/checking-question.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player-base/audio-player-base.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player/audio-player.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player/audio-player.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player/audio-player.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player/audio-player.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-segment-player.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-time-pipe.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/shared.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
Labels: testing not required

#1965 Add Stillness feature flag
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
Labels: testing not required

#1972 SF-2144 Add backout commits tool
  src/Migrations/BackoutCommits/.vscode/launch.json
  src/Migrations/BackoutCommits/.vscode/tasks.json
  src/Migrations/BackoutCommits/BackoutCommits.csproj
  src/Migrations/BackoutCommits/IProgramLogger.cs
  src/Migrations/BackoutCommits/ISFProjectTool.cs
  src/Migrations/BackoutCommits/Program.cs
  src/Migrations/BackoutCommits/ProgramLogger.cs
  src/Migrations/BackoutCommits/SFProjectTool.cs
  src/Migrations/BackoutCommits/Startup.cs
  src/Migrations/BackoutCommits/build-production
  src/Migrations/BackoutCommits/run-dev
Labels: testing not required

#1976 Add service to sync projects after backing out commits
  src/Migrations/BackoutCommits/BackoutCommits.csproj
  src/Migrations/BackoutCommits/ISFProjectTool.cs
  src/Migrations/BackoutCommits/ISyncAllService.cs
  src/Migrations/BackoutCommits/Program.cs
  src/Migrations/BackoutCommits/SFProjectTool.cs
  src/Migrations/BackoutCommits/Startup.cs
  src/Migrations/BackoutCommits/SyncAllService.cs
Labels: testing not required

#1978 SF-2136 Log warnings when SF attempts to push comments to PT
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: ready to test

#1980 Limit commit tool backout to problem dates
  src/Migrations/BackoutCommits/Program.cs
Labels: testing not required

#1977 SF-2079b Fix snackbar panel class
  src/SIL.XForge.Scripture/ClientApp/src/styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts
Labels: will require testing
