Repository sillsdev/web-xforge, pull requests merged in 2023-02, with the labels that each got.

#1695 Disabled HTTP/2 support for Jering
  src/SIL.XForge/Realtime/RealtimeServiceCollectionExtensions.cs
Labels: .NET, testing not required

#1693 Optimize Comment Manager Loading
  src/SIL.XForge.Scripture/Services/ParatextService.cs
Labels: .NET, testing not required

#1666 SF-1808 Add default tag icon for SF notes
  src/RealtimeServer/scriptureforge/models/note-tag.ts
  src/RealtimeServer/scriptureforge/models/note-thread.ts
  src/RealtimeServer/scriptureforge/models/note.ts
  src/RealtimeServer/scriptureforge/models/sf-project.ts
  src/RealtimeServer/scriptureforge/models/translate-config.ts
  src/RealtimeServer/scriptureforge/services/note-thread-migrations.spec.ts
  src/RealtimeServer/scriptureforge/services/note-thread-migrations.ts
  src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts
  src/RealtimeServer/scriptureforge/services/question-service.spec.ts
  src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts
  src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.spec.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.ts
  src/RealtimeServer/scriptureforge/services/text-service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
  src/SIL.XForge.Scripture/Models/Note.cs
  src/SIL.XForge.Scripture/Models/NoteTag.cs
  src/SIL.XForge.Scripture/Models/NoteThread.cs
  src/SIL.XForge.Scripture/Models/NoteThreadChange.cs
  src/SIL.XForge.Scripture/Models/ParatextSettings.cs
  src/SIL.XForge.Scripture/Models/SFProject.cs
  src/SIL.XForge.Scripture/Models/TranslateConfig.cs
  src/SIL.XForge.Scripture/Services/IParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/MockCommentTags.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextNoteExtensions.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: testing complete

#1683 Stop Hangfire jobs deadlocking when a preceding job will not start
  src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs
Labels: .NET, testing not required

#1662 SF-1832 SF-1845 Display Training Progress on the Translate Overview page
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/aligned-word-pair-dto.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/build-dto.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/build-states.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/engine-dto.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/http-client.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/phrase-dto.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/range-dto.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/resource-dto.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/segment-pair-dto.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/translation-engine-stats.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/translation-result-dto.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/word-graph-arc-dto.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/word-graph-dto.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_zh_CN.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/donut-chart/donut-chart.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
Labels: ready to test

#1688 SF-1852 Hide conflict notes from SF
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#1672 SF-1815 Improve adding notes in mobile view for reviewer users
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
Labels: testing complete

#1667 Sync Memory Use and Speed Optimizations
  src/SIL.XForge.Scripture/Services/IParatextService.cs
  src/SIL.XForge.Scripture/Services/NotesFormatter.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  src/SIL.XForge/Realtime/RealtimeJsonService.cs
  src/SIL.XForge/Realtime/RealtimeServer.cs
  test/SIL.XForge.Scripture.Tests/Services/NotesFormatterTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: .NET, testing not required

#1700 SF-1874 Hide community checking from SF reviewers and observers
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-role-info.ts
Labels: testing complete

#1702 Paratext Comment XML Generator
  tools/CommentGenerator/CommentGenerator.csproj
  tools/CommentGenerator/CommentGenerator.sln
  tools/CommentGenerator/Program.cs
Labels: .NET, testing not required

#1698 SF-1870 Parse comment content idempotently
  src/SIL.XForge.Scripture/Services/NotesFormatter.cs
  test/SIL.XForge.Scripture.Tests/Services/NotesFormatterTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: testing complete

#1706 dev: vscode: set prettier and csharpier formatters
  .vscode/settings.json
Labels: testing not required

#1694 SF-1868 Show mobile keyboard when adding a note
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.scss
Labels: testing complete

#1691 SF-1867 Give PT Reviews the same note adding UI as SF Reviewers
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing complete

#1696 SF-1783 Allow admins to answer questions
  src/RealtimeServer/scriptureforge/models/sf-project-rights.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
Labels: testing complete

#1712 doc: migrate to wiki
  README.md
Labels: testing not required

#1714 Fix date format tests for Chromium 110
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/owner/owner.component.spec.ts
Labels: testing not required

#1711 tool: allow running manipulate-sharedb.ts from another dir
  scripts/db_tools/manipulate-sharedb.ts
Labels: testing not required

#1713 tool: add auth0-manage.ts
  scripts/auth0-manage.ts
Labels: testing not required

#1715 SF-1880 Prompt before deleting comment
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
Labels: testing complete

#1718 SF-1882 Rename share-component to share-button-component
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-button.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-button.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-button.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/shared.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
Labels: testing complete

#1709 SF-1878 Mark note read when inserting new notes
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
Labels: will require testing

#1710 SF-1849 Remove secondary linked account paratextId and tokens
  scripts/db_tools/manipulate-sharedb.ts
  src/SIL.XForge/Controllers/UsersRpcController.cs
  src/SIL.XForge/Models/User.cs
  src/SIL.XForge/Services/UserService.cs
  test/SIL.XForge.Tests/Services/UserServiceTests.cs
Labels: testing complete

#1708 SF-1877 Set the ext user attribute on comments when needed
  src/RealtimeServer/scriptureforge/models/note.ts
  src/RealtimeServer/scriptureforge/services/note-thread-migrations.spec.ts
  src/RealtimeServer/scriptureforge/services/note-thread-migrations.ts
  src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
  src/SIL.XForge.Scripture/Models/Note.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextNoteExtensions.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: ready to test

#1720 Add migration to remove percentCompleted from sync property
  src/RealtimeServer/scriptureforge/realtime-server.ts
  src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts
  src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.spec.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.ts
Labels: bug, testing complete
