Repository sillsdev/web-xforge, pull requests merged in 2023-12, with the labels that each got.

#1825 SF-2232 Create simplified navigation sidebar
  .vscode/settings.json
  src/SIL.XForge.Scripture/ClientApp/.storybook/preview.ts
  src/SIL.XForge.Scripture/ClientApp/src/_variables.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/resume-checking.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/chapter-nav/chapter-nav.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/shared.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/activated-project.service.ts
Labels: testing complete

#2191 SF-2378 Update to MDC-based MatTooltip
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
Labels: testing complete

#2203 Remove unneeded mat-slider CSS rules
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.scss
Labels: testing not required

#2204 Update sidebar to use NMT auth guard
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts
Labels: testing not required

#2194 SF-2351 Improve user guidance on draft generation page
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/project-router.guard.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/shared.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/working-animated-indicator/working-animated-indicator.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/supported-back-translation-languages-dialog/supported-back-translation-languages-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/supported-back-translation-languages-dialog/supported-back-translation-languages-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/supported-back-translation-languages-dialog/supported-back-translation-languages-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/supported-back-translation-languages-dialog/supported-back-translation-languages-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: will require testing

#2189 SF-2352 Delete milestones when projects and users are deleted
  src/SIL.XForge/Realtime/RealtimeService.cs
  test/SIL.XForge.Tests/Realtime/RealtimeServiceTests.cs
Labels: testing complete

#2207 SF-2353 Correctly handle a 409 error from Serval
  src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts
  src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
Labels: testing not required

#2213 Fix inconsistent use of icons, and remove unneeded quote
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
Labels: testing not required

#2214 Fix clipping of icons in nav component
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.scss
Labels: testing not required

#2208 SF-2386 Only allow selection of books available in the source and target
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
Labels: testing complete

#2220 SF-2396 Handle pre-translation 409 errors in the editor
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts
  src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
Labels: testing not required

#2186 SF-2342 Remove vertical line question answered indicator
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
Labels: testing complete

#2175 SF-2295 Add support for Adobe Audition timing data
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-utils.ts
Labels: testing complete

#2224 Move strings for text component to checking_en.json and add i18n docs
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/README.md
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#2223 SF-2398 Make tooltips for icon buttons in checking area consistent
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-button.component.html
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
Labels: ready to test

#2226 Refer to draft generation instead of pre-translation
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#2227 Fix link to drafting sign up form
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/pretranslation-signup-url.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/pretranslation-signup-url.service.ts
Labels: testing not required

#2212 SF-2289 Fixed rightward runoff at medium resolutions
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
Labels: testing complete

#2218 SF-2389 Hide pre-translation settings when not approved
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
Labels: testing complete

#2188 SF-2318 Right align suggestions when there's overflow
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.ts
Labels: testing complete

#2209 SF-2382 Fix combined verse support for pre-translation drafts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts
Labels: testing complete

#2230 Integrate new Scripture Forge Logo
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/assets/icons/sf-128x128.png
  src/SIL.XForge.Scripture/ClientApp/src/assets/icons/sf-144x144.png
  src/SIL.XForge.Scripture/ClientApp/src/assets/icons/sf-152x152.png
  src/SIL.XForge.Scripture/ClientApp/src/assets/icons/sf-192x192.png
  src/SIL.XForge.Scripture/ClientApp/src/assets/icons/sf-384x384.png
  src/SIL.XForge.Scripture/ClientApp/src/assets/icons/sf-512x512.png
  src/SIL.XForge.Scripture/ClientApp/src/assets/icons/sf-72x72.png
  src/SIL.XForge.Scripture/ClientApp/src/assets/icons/sf-96x96.png
  src/SIL.XForge.Scripture/ClientApp/src/assets/icons/sf.svg
  src/SIL.XForge.Scripture/ClientApp/src/assets/images/sf.svg
  src/SIL.XForge.Scripture/ClientApp/src/assets/images/sf_logo_with_name.svg
  src/SIL.XForge.Scripture/ClientApp/src/assets/images/sf_logo_with_name_black.svg
  src/SIL.XForge.Scripture/Pages/Index.cshtml
  src/SIL.XForge.Scripture/Pages/Shared/_Layout.cshtml
  src/SIL.XForge.Scripture/wwwroot/css/sf.min.css
  src/SIL.XForge.Scripture/wwwroot/favicon.ico
  src/SIL.XForge.Scripture/wwwroot/images/banner-book-curve.svg
  src/SIL.XForge.Scripture/wwwroot/images/multi-devices.svg
  src/SIL.XForge.Scripture/wwwroot/scss/_header.scss
  src/SIL.XForge.Scripture/wwwroot/scss/_home.scss
Labels: Critical Path, testing not required

#2199 SF-2381 Support phrase level audio scripture playback on questions
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-test.utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts
Labels: testing complete

#2232 Improve sidebar headings
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.scss
Labels: Critical Path, testing not required

#2210 SF-2354 Display Serval Build diagnostic information to System Admins
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/build-dto.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
  src/SIL.XForge.Scripture/Controllers/MachineApiV2Controller.cs
  src/SIL.XForge.Scripture/Models/ServalBuildAdditionalInfo.cs
  src/SIL.XForge.Scripture/Models/ServalBuildDto.cs
  src/SIL.XForge.Scripture/Services/IMachineApiService.cs
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiV2ControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
Labels: testing complete

#2233 Update translate link to "Edit & review"
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: Critical Path, testing not required

#2216 SF-2301 Enable resolving note threads in SF
  src/RealtimeServer/scriptureforge/models/sf-project-rights.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
Labels: ready to test

#2200 SF-2383 Adjust and add styling options to notice component
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/join/join.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/info/info.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.types.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/shared.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flags-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flags-dialog.component.spec.ts
Labels: enhancement

#2235 SF-2406 Support timing files with headings
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts
Labels: Critical Path, testing complete

#2222 SF-2379 Allow selection of draft translation books
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: new feature, Critical Path, testing complete

#2229 SF-2397 Allow rebuilding when Serval data is missing from SF or Serval
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
  src/SIL.XForge.Scripture/Services/IMachineProjectService.cs
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
Labels: Critical Path, will require testing

#2237 audio: localize Uploading string
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
Labels: testing not required

#2242 SF-2393 Display unusable drafting books
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: new feature, will require testing

#2247 Fix minor items related to SF-2393
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
Labels: testing not required

#2231 SF-2309 Support for combined verses in the target text
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts
Labels: Critical Path, ready to test

#2239 SF-2409 Remove tokenization of data sent to Serval
  src/SIL.XForge.Scripture/Models/ISFText.cs
  src/SIL.XForge.Scripture/Models/SFTextSegment.cs
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/Services/ISFTextCorpusFactory.cs
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  src/SIL.XForge.Scripture/Services/SFBiblicalTermsText.cs
  src/SIL.XForge.Scripture/Services/SFScriptureText.cs
  src/SIL.XForge.Scripture/Services/SFTextCorpusFactory.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MockText.cs
  test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs
Labels: Critical Path, will require testing

#2246 Fix error in TranslateOverview retrain unit test
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
Labels: testing not required

#2252 Enable Serval support across all environments
  src/SIL.XForge.Scripture/appsettings.json
Labels: testing not required

#2245 SF-2412 Overwriting audio timing data doesn't parse correctly
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts
Labels: testing complete

#2244 Update CSharpier to 0.26.7
  .config/dotnet-tools.json
  src/Migrations/BackoutCommits/Program.cs
  src/Migrations/BackoutCommits/SyncAllService.cs
  src/Migrations/PTDDCloneAll.Tests/CloneAllServiceTests.cs
  src/Migrations/PTDDCloneAll/PTDDSyncRunner.cs
  src/Migrations/PtdaSyncAll.Tests/PtdaSyncRunnerTests.cs
  src/Migrations/PtdaSyncAll.Tests/SyncAllServiceTests.cs
  src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs
  src/Migrations/PtdaSyncAll/SyncAllService.cs
  src/Migrations/ServalMigration/ServalMigrator.cs
  src/Migrations/SourceTargetSplitting/ObjectMigrator.cs
  src/SIL.XForge.Scripture/Controllers/AnonymousController.cs
  src/SIL.XForge.Scripture/Controllers/LanguageController.cs
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  src/SIL.XForge.Scripture/Services/MachineServiceCollectionExtensions.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  src/SIL.XForge.Scripture/Services/SFBiblicalTermsText.cs
  src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge/Services/AuthServiceCollectionExtensions.cs
  src/SIL.XForge/Services/ProjectService.cs
  src/SIL.XForge/Services/UserService.cs
  test/SIL.XForge.Scripture.Tests/Controllers/AnonymousControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiV2ControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsRpcControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/AnonymousServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/InternetSharedRepositorySourceProviderTests.cs
  test/SIL.XForge.Scripture.Tests/Services/JwtInternetSharedRepositorySourceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/PreTranslationServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SyncServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/TransceleratorServiceTests.cs
  test/SIL.XForge.Tests/Realtime/ConnectionTests.cs
  test/SIL.XForge.Tests/Realtime/RealtimeServiceTests.cs
  test/SIL.XForge.Tests/Services/ProjectServiceTests.cs
  test/SIL.XForge.Tests/Services/UserServiceTests.cs
Labels: .NET, testing not required

#2253 Fix alignment in BookChapterChooser component
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.scss
Labels: testing not required

#2217 SF-2388 Update to RxJS 7
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/anonymous.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth0.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth0.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts
Labels: ready to test

#2257 Updated favicon
  src/SIL.XForge.Scripture/ClientApp/src/favicon.ico
  src/SIL.XForge.Scripture/wwwroot/favicon.ico
Labels: testing not required

#2228 SF-2403 Fix skip previous or next to skip past phrases
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
Labels: testing complete

#2241 SF-2411 Restrict resolve option on dialog when restricted tags used
  src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts
  src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: testing complete

#2248 SF-2337 Replace ngx-avatar with custom component
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/users/users.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar-testing.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar-testing.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/owner/owner.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/owner/owner.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xforge-common.module.ts
Labels: ready to test

#2261 SF-2431 Sort books on draft generation page
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
Labels: testing not required

#2249 SF-2425 Show user pretranslation failure info
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
  src/SIL.XForge.Scripture/Controllers/MachineApiV2Controller.cs
  src/SIL.XForge.Scripture/Services/IMachineApiService.cs
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiV2ControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
Labels: ready to test

#2260 Remove use of Material legacy form fields
  src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
Labels: testing not required

#2259 SF-2375 Upgrade legacy mat-tabs
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
Labels: testing not required

#2225 SF-2399 Sort books in community checking book list
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.stories.ts
Labels: ready to test

#2263 SF-2374 Upgrade legacy mat-table
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-confirmation-dialog/import-question-confirmation-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-confirmation-dialog/import-questions-confirmation-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
Labels: testing not required
