Repository sillsdev/web-xforge, pull requests merged in 2023-04, with the labels that each got.

#1775 SF-1935 - Close note bottom sheet when not in use
  src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/overlay-container.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/overlay-container.ts
Labels: testing complete

#1773 SF-1937 - Hide user assignment in the notes dialog for commenters
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
Labels: testing complete

#1772 SF-1932 - Store updated avatar URL in Auth0 user metadata
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts
  src/SIL.XForge/Services/AuthService.cs
  src/SIL.XForge/Services/UserService.cs
  test/SIL.XForge.Tests/Services/UserServiceTests.cs
Labels: testing complete

#1774 SF-1917 Add reviewer label on note content
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
Labels: ready to test

#1780 Add in compatibility endpoints for old clients using share keys
  src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
Labels: testing not required

#1782 Fix for note dialog tests breaking for some runs
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
Labels: testing not required

#1784 Fix styles leaking from import question dialog
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss
Labels: testing complete

#1781 SF-1946 Fix text deleted when synchronizing with note feature enabled
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
Labels: testing complete

#1776 SF-1924 PT comments on SF community checking answers lost after sync
  src/RealtimeServer/common/services/project-data-service.spec.ts
  src/RealtimeServer/common/services/project-data-service.ts
  src/RealtimeServer/scriptureforge/models/comment.ts
  src/RealtimeServer/scriptureforge/models/note.ts
  src/RealtimeServer/scriptureforge/services/question-migrations.spec.ts
  src/RealtimeServer/scriptureforge/services/question-migrations.ts
  src/RealtimeServer/scriptureforge/services/question-service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts
  src/SIL.XForge.Scripture/Models/Answer.cs
  src/SIL.XForge.Scripture/Models/Comment.cs
  src/SIL.XForge.Scripture/Models/Note.cs
  src/SIL.XForge.Scripture/Services/IParatextNotesMapper.cs
  src/SIL.XForge.Scripture/Services/NotesFormatter.cs
  src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: ready to test

#1765 SF-1923 Use bottom sheet for commenters to add new notes
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#1777 SF-1944 Allow translators to edit note thread position
  src/RealtimeServer/scriptureforge/models/sf-project-rights.ts
  src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts
Labels: ready to test

#1787 SF-1953 Fix for checker receiving a 403 error when deleting an answer
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
Labels: testing complete

#1779 SF-1897 Deselect the current verse selection when opening note dialog
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: ready to test

#1703 tool: allow email arg to db-token-info
  scripts/db_tools/db-token-info.ts
Labels: testing not required

#1786 Upgrade to Storybook 7
  src/SIL.XForge.Scripture/ClientApp/.storybook/main.ts
  src/SIL.XForge.Scripture/ClientApp/.storybook/preview-head.html
  src/SIL.XForge.Scripture/ClientApp/.storybook/preview.ts
  src/SIL.XForge.Scripture/ClientApp/.storybook/tsconfig.json
  src/SIL.XForge.Scripture/ClientApp/angular.json
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-button.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n-story.module.ts
Labels: testing not required

#1796 SF-1888 Change role names for SF reviewers and observers
  .vscode/settings.json
  src/RealtimeServer/scriptureforge/models/sf-project-role.ts
  src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-role-info.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/Models/SFProjectRole.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: testing not required

#1797 SF-1414 Fix book sort order in Scripture Chooser & Checking Overview
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.ts
Labels: testing complete

#1793 Dependency Updates
  .config/dotnet-tools.json
  README.md
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge/SIL.XForge.csproj
  test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
  test/SIL.XForge.Tests/SIL.XForge.Tests.csproj
Labels: testing not required

#1801 Add Mongo query to count answers by month
  mongodb/Questions/CountAnswersByMonth.mongodb
Labels: testing not required

#1800 Update Storybook stories
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-button.stories.ts
Labels: testing not required

#1799 Fix poor quality translation suggestions
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/Services/SFScriptureText.cs
Labels: testing not required

#1802 Add Mongo script to drop databases
  mongodb/databases/DropXFDatabases.js
Labels: testing not required

#1804 SF-1969 Do not add a tag id to notes on existing thread
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing complete

#1803 Add font size stories and fix font size picker in RTL mode
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.stories.ts
Labels: testing not required

#1805 Add MDC dialog stories
  src/SIL.XForge.Scripture/ClientApp/.storybook/main.ts
  src/SIL.XForge.Scripture/ClientApp/.storybook/preview.ts
  src/SIL.XForge.Scripture/ClientApp/.storybook/story-utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/mdc-dialog.stories.ts
Labels: testing not required

#1806 Add Mongo query to show trends in suggestions and edits
  mongodb/TranslateMetrics/CountEditsByMonth.mongodb
Labels: testing not required

#1808 Add Chromatic
  .github/workflows/chromatic.yml
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
Labels: testing not required
