Repository sillsdev/web-xforge, pull requests merged in 2023-01, with the labels that each got.

#1651 Configure Jering to use HTTP/2
  src/SIL.XForge/Realtime/RealtimeServiceCollectionExtensions.cs
Labels: .NET, testing not required

#1652 Update the RealtimeServer Connection to be IAsyncDisposable
  src/SIL.XForge.Scripture/Controllers/SFProjectsUploadController.cs
  src/SIL.XForge.Scripture/Services/SFBuildHandler.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge.Scripture/Services/SFTextCorpusFactory.cs
  src/SIL.XForge.Scripture/Services/SyncService.cs
  src/SIL.XForge/Realtime/Connection.cs
  src/SIL.XForge/Realtime/IConnection.cs
  src/SIL.XForge/Realtime/IRealtimeServer.cs
  src/SIL.XForge/Realtime/MemoryConnection.cs
  src/SIL.XForge/Realtime/RealtimeServer.cs
  src/SIL.XForge/Services/ProjectService.cs
  src/SIL.XForge/Services/UserService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
  test/SIL.XForge.Tests/Services/UserServiceTests.cs
Labels: .NET, testing not required

#1650 Fix remaining CodeQL issues in Unit Tests
  src/SIL.XForge.Scripture/Services/JwtInternetSharedRepositorySource.cs
  src/SIL.XForge.Scripture/Services/SFScriptureText.cs
  test/SIL.XForge.Scripture.Tests/Services/ComparableProjectPermissionManager.cs
  test/SIL.XForge.Scripture.Tests/Services/InternetSharedRepositorySourceProviderTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
  test/SIL.XForge.Tests/Realtime/RichText/DeltaTests.cs
Labels: .NET, testing not required

#1643 doc: add section on invalidating refresh tokens
  README.md
Labels: testing not required

#1641 doc: add section Cleaning
  README.md
Labels: testing not required

#1653 Update .NET dependencies
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge/SIL.XForge.csproj
  test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
  test/SIL.XForge.Tests/SIL.XForge.Tests.csproj
Labels: .NET, testing not required

#1656 SF-1421 The correct first chapter is now selected if chapter 1 is missing from a book
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing complete

#1639 SF-1618 SF-1619 Make question import more flexible
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#1647 Simplify usage of confirmation dialog
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts
Labels: testing not required

#1657 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_zh_CN.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_zh_CN.json
Labels: testing not required

#1658 Update jsonwebtoken and json5 to fix vulnerabilities
  src/RealtimeServer/common/web-socket-stream-listener.ts
  src/RealtimeServer/package-lock.json
  src/RealtimeServer/package.json
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
Labels: testing not required

#1655 SF-1313 The sync status now updates if another user starts a sync
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts
Labels: testing complete

#1661 Fixed TypeScript Lint Issues
  src/SIL.XForge.Scripture/ClientApp/src/typings/quill.d.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-utils.ts
Labels: testing not required

#1664 Updated workflow step actions to node.js v16
  .github/workflows/ci-lint-prettier.yml
  .github/workflows/ci-production-build.yml
Labels: testing not required

#1660 Update dependencies to .NET 6.0.13
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge/SIL.XForge.csproj
Labels: .NET, testing not required

#1575 SF-1802 Throw exception when registry returns error fetching project
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: testing not required

#1665 SF-1592 Font size is not changing in the note dialog text
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
Labels: testing complete

#1668 SF-1779 Only update resource access for Paratext users on sync
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: .NET, testing complete

#1654 SF-1844 Use SignalR for Sync Progress
  src/RealtimeServer/scriptureforge/models/sync.ts
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/project-notification.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts
  src/SIL.XForge.Scripture/Models/ProgressState.cs
  src/SIL.XForge.Scripture/Models/Sync.cs
  src/SIL.XForge.Scripture/Services/INotifier.cs
  src/SIL.XForge.Scripture/Services/NotificationHub.cs
  src/SIL.XForge.Scripture/Services/NotificationHubExtensions.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  src/SIL.XForge.Scripture/Services/SyncProgress.cs
  src/SIL.XForge.Scripture/Services/SyncService.cs
  src/SIL.XForge.Scripture/Startup.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SyncServiceTests.cs
Labels: testing complete

#1670 SF-1851 Update the source text in the editor when the target text changes
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing complete

#1674 tool: show jwt issuedAt
  scripts/db_tools/show-jwt.ts
Labels: testing not required

#1673 SF-1844a Add Authorization to the SignalR hub
  src/SIL.XForge.Scripture/ClientApp/src/app/core/project-notification.service.ts
  src/SIL.XForge.Scripture/Services/NotificationHub.cs
  src/SIL.XForge.Scripture/Startup.cs
  src/SIL.XForge/Controllers/UrlConstants.cs
  src/SIL.XForge/Services/AuthServiceCollectionExtensions.cs
Labels: testing not required

#1677 Add return type warning to eslint
  src/SIL.XForge.Scripture/ClientApp/.eslintrc.json
Labels: testing not required

#1678 Save sync metrics logs to DB as they are created
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
Labels: testing not required

#1626 SF-1823 Web API for Machine API
  src/Migrations/MachineApiMigration/MachineApiMigration.csproj
  src/Migrations/MachineApiMigration/MachineApiMigration.sln
  src/Migrations/MachineApiMigration/MachineApiMigrator.cs
  src/Migrations/MachineApiMigration/MigratorFeatureSessionManager.cs
  src/Migrations/MachineApiMigration/Program.cs
  src/Migrations/MachineApiMigration/Properties/launchSettings.json
  src/Migrations/MachineApiMigration/Startup.cs
  src/SIL.XForge.Scripture/ClientApp/src/app/core/machine-http-client.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts
  src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
  src/SIL.XForge.Scripture/Models/FeatureFlags.cs
  src/SIL.XForge.Scripture/Models/MachineApi.cs
  src/SIL.XForge.Scripture/Services/IMachineApiService.cs
  src/SIL.XForge.Scripture/Services/IMachineBuildService.cs
  src/SIL.XForge.Scripture/Services/IParatextService.cs
  src/SIL.XForge.Scripture/Services/ISFProjectService.cs
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  src/SIL.XForge.Scripture/Services/MachineBuildService.cs
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  src/SIL.XForge.Scripture/Services/MachineServiceBase.cs
  src/SIL.XForge.Scripture/Services/MachineServiceCollectionExtensions.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge.Scripture/Services/SFScriptureText.cs
  src/SIL.XForge.Scripture/appsettings.Development.json
  src/SIL.XForge.Scripture/appsettings.Staging.json
  src/SIL.XForge.Scripture/appsettings.Testing.json
  src/SIL.XForge.Scripture/appsettings.json
  src/SIL.XForge/Realtime/Connection.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineBuildServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
  test/SIL.XForge.Tests/Realtime/ConnectionTests.cs
Labels: testing complete

#1679 Update cookiejar and ua-parser-js using npm audit fix
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
Labels: testing not required

#1676 SF-1854 Fix note thread permissions
  src/RealtimeServer/common/models/project-rights.ts
  src/RealtimeServer/common/services/project-data-service.spec.ts
  src/RealtimeServer/scriptureforge/models/sf-project-rights.ts
Labels: blocker, will require testing

#1685 Disable HTTP/2 support for Jering on sf-live
  src/SIL.XForge/Realtime/RealtimeServiceCollectionExtensions.cs
Labels: .NET, fix recent change, testing not required

#1684 Revert "Save sync metrics logs to DB as they are created"
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
Labels: testing not required
