Repository sillsdev/web-xforge, pull requests merged in 2023-05, with the labels that each got.

#1792 SF-1958 Show the commenter selected verse on bottom sheet
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing complete

#1812 SF-1988 Support for resources with duplicate short names
  src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
  src/SIL.XForge.Scripture/Services/SFScrTextCollection.cs
Labels: will require testing

#1798 SF-1973 Flag all chapters of extra-Biblical books as invalid
  src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
  test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
Labels: testing complete

#1816 Fixed Kayah Li script on Windows
  src/SIL.XForge.Scripture/ClientApp/src/_text.scss
  src/SIL.XForge.Scripture/ClientApp/src/index.html
Labels: ready to test

#1817 Fix height of send button in share control
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss
Labels: testing not required

#1818 Add Mongo query to analyze use of answers and comments
  mongodb/Questions/AnswerStats.mongodb
Labels: testing not required

#1828 Fix user menu min width
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
Labels: testing not required

#1827 Add write-status stories
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.stories.ts
Labels: testing not required

#1791 SF-1917 Add reviewer name to note thread in PT
  src/SIL.XForge.Scripture/Services/IParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  src/SIL.XForge/Services/IUserService.cs
  src/SIL.XForge/Services/UserService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: testing complete

#1832 Fix share control appearance on mobile
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss
Labels: testing not required

#1826 Add translation suggestion story and fix RTL suggestions
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.stories.ts
Labels: testing not required

#1819 Add query to count projects with lots of edits
  mongodb/Texts/CountProjectsWithEdits.mongodb
Labels: testing not required

#1829 SF-2000 Update audio recorder component
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts
Labels: ready to test

#1838 SF-2007 Enable Lao localization in production
  src/SIL.XForge.Scripture/locales.json
Labels: testing complete

#1834 SF-2004 Make appAutofocus directive work with non-MDC components
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/autofocus.directive.ts
Labels: testing complete

#1814 SF-1996 Add note threads when book is newly added on a sync
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: ready to test

#1844 SF-2014 Convert checking comment form to Material
  .vscode/settings.json
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
Labels: testing complete

#1835 SF-2002 Create SF user label only for user IDs without a paratext role
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: ready to test

#1833 SF-2003 Fix note anchors not updated after notes loaded
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: ready to test

#1849 Make Codecov checks informational only
  codecov.yml
Labels: testing not required

#1823 SF-1998 Fix help links
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.ts
  src/SIL.XForge.Scripture/locales.json
Labels: testing complete

#1847 SF-2021 Note tags are no longer updated on every sync
  src/SIL.XForge.Scripture/Services/ChapterEqualityComparer.cs
  src/SIL.XForge.Scripture/Services/DictionaryComparer.cs
  src/SIL.XForge.Scripture/Services/NoteTagEqualityComparer.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ChapterEqualityComparerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/DictionaryComparerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/NoteTagEqualityComparerTests.cs
Labels: testing complete

#1743 SF-1712 - Transparent authentication
  src/RealtimeServer/scriptureforge/models/sf-project.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/anonymous.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth0.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth0.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/url-constants.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user-projects.service.ts
  src/SIL.XForge.Scripture/Controllers/AnonymousController.cs
  src/SIL.XForge.Scripture/Controllers/CookieConstants.cs
  src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
  src/SIL.XForge.Scripture/Models/AnonymousShareKeyResponse.cs
  src/SIL.XForge.Scripture/Models/CheckShareKeyRequest.cs
  src/SIL.XForge.Scripture/Models/GenerateAccountRequest.cs
  src/SIL.XForge.Scripture/Models/SFProject.cs
  src/SIL.XForge.Scripture/Models/ValidShareKey.cs
  src/SIL.XForge.Scripture/Services/AnonymousService.cs
  src/SIL.XForge.Scripture/Services/IAnonymousService.cs
  src/SIL.XForge.Scripture/Services/ISFProjectService.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge.Scripture/Services/SFServiceCollectionExtensions.cs
  src/SIL.XForge/Controllers/UrlConstants.cs
  src/SIL.XForge/Models/ShareKey.cs
  src/SIL.XForge/Models/TransparentAuthenticationCredentials.cs
  src/SIL.XForge/Services/AuthService.cs
  src/SIL.XForge/Services/IAuthService.cs
  src/SIL.XForge/Services/ISecurityService.cs
  src/SIL.XForge/Services/ProjectService.cs
  src/SIL.XForge/Services/SecurityService.cs
  src/SIL.XForge/Services/UserService.cs
  test/SIL.XForge.Scripture.Tests/Controllers/AnonymousControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/AnonymousServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: will require testing

#1853 Increase Hangfire Timeout to 3 hours
  src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs
Labels: testing not required

#1852 SF-1960 Set display name when a user signs up with a phone number
  src/SIL.XForge/Services/AuthService.cs
  src/SIL.XForge/Services/IAuthService.cs
  src/SIL.XForge/Services/UserService.cs
  test/SIL.XForge.Tests/Services/UserServiceTests.cs
Labels: testing complete

#1842 SF-1459 Fix checking overview question list not always updating
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
Labels: ready to test

#1854 SF-2029 Fixed Code Coverage failing Pull Requests
  codecov.yml
Labels: testing complete

#1858 Increase Hangfire Timeout to 4 hours
  src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs
Labels: testing not required

#1859 tool: Update Chromatic workflow to build tip of branch
  .github/workflows/chromatic.yml
Labels: testing not required

#1865 Update NPM dependencies flagged as vulnerable
  scripts/db_tools/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
Labels: dependencies, testing not required

#1836 SF-2006 Checking overview page to Material
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
Labels: testing complete

#1848 SF-2010 Convert system admin page to material
  src/SIL.XForge.Scripture/ClientApp/.storybook/preview.ts
  src/SIL.XForge.Scripture/ClientApp/.storybook/util/mat-dialog-launch.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-delete-dialog.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/system-administration.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/system-administration.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
Labels: testing complete

#1856 SF-2017 Convert suggestions component to Material
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.stories.ts
Labels: testing complete

#1864 SF-1934 Fix RTL language marker not recognized in combined verses
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
Labels: testing complete

#1867 SF-1506 Maintain consistent font size for va markers
  src/SIL.XForge.Scripture/ClientApp/src/_usx.scss
Labels: testing not required

#1863 SF-2016 Convert 'write status' component to material
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.stories.ts
Labels: testing complete

#1877 log: resource needs updating or not
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
Labels: testing not required

#1824 tool: enhance time output from text-doc-history
  scripts/db_tools/text-doc-history.js
Labels: testing not required
