Repository sillsdev/web-xforge, pull requests merged in 2023-06, with the labels that each got.

#1851 SF-2013 Convert error dialog to Material
  src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/mdc-dialog.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error/error.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
Labels: testing complete

#1874 SF-2008 Justified share dialog buttons without reversing the row direction
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.ts
Labels: testing complete

#1872 SF-1939 Improve error message for invalid invitations
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/join/join.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: testing not required

#1871 SF-2046 Maintain the user's current segment after closing the note di…
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing complete

#1883 Enable Chromatic TurboSnap
  .github/workflows/chromatic.yml
Labels: testing not required

#1884 SF-2057 Fix error opening note dialog
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: fix recent change, blocker

#1866 SF-2036 Checking comments components use mat-button
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.scss
Labels: testing complete

#1890 SF-2069 Improve suggestion component
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n-story.module.ts
Labels: testing complete

#1840 SF-1989 Update users table to material
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.ts
Labels: testing complete

#1873 SF-2047 MDC to Material checking answers
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-answered-dialog/question-answered-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-answered-dialog/question-answered-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/mdc-dialog.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
Labels: testing complete

#1893 SF-2075 Add Scripture audio feature flag
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
Labels: testing not required

#1860 SF-2031 Fix handling of unexpected errors in join component
  src/SIL.XForge.Scripture/Controllers/AnonymousController.cs
  test/SIL.XForge.Scripture.Tests/Controllers/AnonymousControllerTests.cs
Labels: testing not required

#1894 SF-2071 Checking Audio to Material
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/users/users.component.html
Labels: testing complete

#1895 SF-2077 Fix styling of role selection menu
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss
Labels: testing complete

#1885 SF-2052 File and Corpora Patching for Serval
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiV2ControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MockHttpMessageHandler.cs
Labels: testing not required

#1900 SF-2082 Update TypeScript to 4.8.4
  src/RealtimeServer/package-lock.json
  src/RealtimeServer/package.json
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
Labels: testing not required

#1899 SF-2081 Create container for audio component over chapter
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
Labels: testing not required

#1896 Update I18nStoryModule to work with I18nService
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n-story.module.ts
Labels: testing not required

#1906 Fix support for developers with the .NET SDK 7.0.304 installed
  .editorconfig
Labels: testing not required

#1862 SF-2015 Convert font size component to material
  src/SIL.XForge.Scripture/ClientApp/.storybook/preview.ts
  src/SIL.XForge.Scripture/ClientApp/angular.json
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/overlay-container.ts
Labels: testing complete

#1898 SF-2080 Create circular audio progress component
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.stories.ts
Labels: testing not required

#1901 SF-2065 Update the selected verse when user opens a note dialog
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: ready to test

#1888 SF-1814 User Invites Settings
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/info/info.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/info/info.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/info/info.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/info/info.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/shared.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/styles.scss
Labels: ready to test

#1907 SF-2073 Replaced Project Deleted dialog with built-in
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project-deleted-dialog/project-deleted-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/project-deleted-dialog/project-deleted-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/mdc-dialog.stories.ts
Labels: ready to test

#1914 Update .NET dependencies and test dependencies
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge/SIL.XForge.csproj
  test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
  test/SIL.XForge.Tests/SIL.XForge.Tests.csproj
Labels: testing not required

#1904 SF-2083 Update Project WritingSystem.Tag on Sync
  src/SIL.XForge.Scripture/Models/ParatextSettings.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: testing complete

#1845 SF-1972 Sync Speed Improvements
  src/SIL.XForge.Scripture/Models/ParatextSyncResults.cs
  src/SIL.XForge.Scripture/Models/SyncMetrics.cs
  src/SIL.XForge.Scripture/Services/IParatextDataHelper.cs
  src/SIL.XForge.Scripture/Services/IParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextDataHelper.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Models/ParatextSyncResultsTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
  tools/RepoInfo/Program.cs
  tools/RepoInfo/RepoInfo.csproj
  tools/RepoInfo/RepoInfo.sln
Labels: testing complete

#1916 SF-2093 Add Developer Web API Documentation
  src/SIL.XForge.Scripture/Controllers/AnonymousController.cs
  src/SIL.XForge.Scripture/Controllers/LanguageController.cs
  src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
  src/SIL.XForge.Scripture/Controllers/ParatextController.cs
  src/SIL.XForge.Scripture/Controllers/SFProjectsUploadController.cs
  src/SIL.XForge.Scripture/Models/Sync.cs
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/Services/ApiDocumentationExtensions.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  src/SIL.XForge.Scripture/Services/SFDblRestClientFactory.cs
  src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge.Scripture/Startup.cs
  test/SIL.XForge.Scripture.Tests/Controllers/AnonymousControllerTests.cs
Labels: testing not required

#1918 Add comment to csproj file
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
Labels: testing not required

#1912 SF-2086 Delete thread doc if all notes removed in Paratext
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: ready to test

#1917 SF-2060 Suppress SignalR errors related to user navigation
  src/SIL.XForge.Scripture/ClientApp/src/app/core/project-notification.service.ts
Labels: testing complete

#1911 SF-2087 Show note thread on verses with letters
  src/RealtimeServer/scriptureforge/models/verse-ref-data.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: ready to test

#1913 SF-2088 Add model for Scripture Audio
  src/RealtimeServer/scriptureforge/models/audio-timing.ts
  src/RealtimeServer/scriptureforge/models/sf-project-rights.ts
  src/RealtimeServer/scriptureforge/models/text-audio.ts
  src/RealtimeServer/scriptureforge/models/text-info.ts
  src/RealtimeServer/scriptureforge/realtime-server.ts
  src/RealtimeServer/scriptureforge/services/text-audio-migrations.ts
  src/RealtimeServer/scriptureforge/services/text-audio-service.spec.ts
  src/RealtimeServer/scriptureforge/services/text-audio-service.ts
  src/SIL.XForge.Scripture/Models/AudioTiming.cs
  src/SIL.XForge.Scripture/Models/Chapter.cs
  src/SIL.XForge.Scripture/Models/TextAudio.cs
  src/SIL.XForge.Scripture/Realtime/SFRealtimeServiceCollectionExtensions.cs
Labels: testing not required

#1920 SF-1991 Record Scripture Forge Version on Sync
  src/SIL.XForge.Scripture/Migrator.cs
  src/SIL.XForge.Scripture/Models/SyncMetrics.cs
  src/SIL.XForge.Scripture/Services/JwtRestClient.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  src/SIL.XForge.Scripture/ViewComponents/FooterViewComponent.cs
  src/SIL.XForge/ExceptionLogging/ExceptionHandlerServiceCollectionExtensions.cs
  src/SIL.XForge/Realtime/RealtimeService.cs
  src/SIL.XForge/Utils/Product.cs
Labels: testing not required

#1923 Revert "SF-1972 Sync Speed Improvements (#1845)"
  src/SIL.XForge.Scripture/Models/ParatextSyncResults.cs
  src/SIL.XForge.Scripture/Models/SyncMetrics.cs
  src/SIL.XForge.Scripture/Services/IParatextDataHelper.cs
  src/SIL.XForge.Scripture/Services/IParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextDataHelper.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Models/ParatextSyncResultsTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
  tools/RepoInfo/Program.cs
  tools/RepoInfo/RepoInfo.csproj
  tools/RepoInfo/RepoInfo.sln
Labels: testing not required

#1909 SF-2059 Provide unique data ids to new note threads
  src/RealtimeServer/scriptureforge/models/note-thread.ts
  src/RealtimeServer/scriptureforge/services/note-thread-migrations.spec.ts
  src/RealtimeServer/scriptureforge/services/note-thread-migrations.ts
  src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/Models/NoteThread.cs
  src/SIL.XForge.Scripture/Models/NoteThreadChange.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: ready to test

#1925 tool: show-project: be resilient to unexpected db data
  scripts/db_tools/show-projects.ts
Labels: testing not required

#1927 SF-2112b Add button to delete timing data
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
  src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
  src/SIL.XForge.Scripture/Services/ISFProjectService.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
Labels: testing not required

#1928 SF-2106 Add UI for scripture audio component
  src/RealtimeServer/scriptureforge/models/text-audio.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-type-registry.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-audio-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
Labels: testing not required

#1931 SF-2112c Improve mock audio files
  src/SIL.XForge.Scripture/ClientApp/.eslintrc.json
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
Labels: testing not required

#1932 SF-2104 Add basic question component
  src/SIL.XForge.Scripture/ClientApp/src/app/checking-question/checking-question.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking-question/checking-question.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking-question/checking-question.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/shared.module.ts
Labels: testing not required

#1922 SF-2111 Add Mongo Milestone Adapter
  src/RealtimeServer/common/index.ts
  src/RealtimeServer/common/realtime-server.ts
  src/RealtimeServer/package-lock.json
  src/RealtimeServer/package.json
  src/RealtimeServer/scriptureforge/realtime-server.ts
  src/RealtimeServer/typings/sharedb-milestone-mongo.d.ts
  src/RealtimeServer/typings/sharedb/index.d.ts
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
Labels: testing not required

#1935 Minor improvements to users page roles paragraph
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.scss
Labels: testing not required

#1936 Move join component strings to checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#1926 tool: manipulate-sharedb: use utils by namespace
  scripts/db_tools/manipulate-sharedb.ts
Labels: testing not required

#1937 Add Mongo script to export questions
  mongodb/Questions/ExportQuestions.mongodb
Labels: testing not required

#1940 Fix await using statements for ConnectAsync()
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
Labels: testing not required

#1930 SF-1502 Make email validation more flexible
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xfvalidators.ts
Labels: testing complete

#1929 SF-2120 Add ability to disable the document cache
  src/SIL.XForge/Configuration/RealtimeOptions.cs
  src/SIL.XForge/Realtime/Connection.cs
  src/SIL.XForge/Realtime/RealtimeService.cs
  test/SIL.XForge.Tests/Realtime/ConnectionTests.cs
Labels: testing complete

#1938 SF-2122 Adjust comment FAB for RTL target language
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing complete
