Repository sillsdev/web-xforge, pull requests merged in 2024-09, with the labels that each got.

#2698 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_de.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_npi.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_zh_CN.json
Labels: testing not required

#2694 Remove obsolete scripture audio feature flag
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
Labels: testing not required

#2667 SF-2886 Allow adding a draft book to a different project
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#2684 SF-2844 Notify user resource failed to load due to being offline
  src/SIL.XForge.Scripture/ClientApp/src/app/core/project-notification.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
Labels: ready to test

#2697 SF-2725 Show Apply Draft for invalid and unsupported USFM cases
  src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts
  src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
  src/SIL.XForge.Scripture/Services/ISFProjectService.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: ready to test

#2700 Fix @for track expression in error dialog
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.html
Labels: testing not required

#2701 Allow downloading resources from Serval admin page, and other fixups
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
Labels: testing not required

#2679 SF-2928 Allow Serval admins to download drafts
  src/SIL.XForge.Scripture/ClientApp/angular.json
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts
  src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
  src/SIL.XForge.Scripture/Models/MachineApi.cs
  src/SIL.XForge.Scripture/Services/IMachineApiService.cs
  src/SIL.XForge.Scripture/Services/IPreTranslationService.cs
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  src/SIL.XForge.Scripture/Services/PreTranslationService.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/PreTranslationServiceTests.cs
Labels: testing not required

#2695 SF-2929 Add missing unit tests in ParatextService
  src/SIL.XForge.Scripture/Models/BiblicalTermsChanges.cs
  src/SIL.XForge.Scripture/Services/IScrTextCollection.cs
  src/SIL.XForge.Scripture/Services/LazyScrTextCollection.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
  test/SIL.XForge.Scripture.Tests/Services/MockLazyScrTextCollection.cs
  test/SIL.XForge.Scripture.Tests/Services/MockResourceScrText.cs
  test/SIL.XForge.Scripture.Tests/Services/MockScrLanguage.cs
  test/SIL.XForge.Scripture.Tests/Services/MockScrText.cs
  test/SIL.XForge.Scripture.Tests/Services/MockZippedProjectFileManager.cs
  test/SIL.XForge.Scripture.Tests/Services/MockZippedResourcePasswordProvider.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: testing not required

#2702 Wrap long lines in draft config on Serval project page
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.scss
Labels: testing not required

#2704 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_de.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_npi.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_zh_CN.json
Labels: testing not required

#2705 Remove unneeded optional chaining in templates
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.html
Labels: testing not required

#2696 SF-2947 Only update interface language via UI
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
Labels: ready to test

#2703 SF-2955 Fix checking question layout
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
Labels: Critical Path, ready to test

#2706 Display project type for sources on Serval admin page
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
Labels: testing not required

#2691 SF-2895 Add recording visualizer to the audio recorder dialog
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts
Labels: testing not required

#2708 SF-2934 Notify user when joining a project fails
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
Labels: ready to test

#2625 SF-2885 Fix project deleted message being shown after deleting project
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
Labels: testing complete

#2716 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_de.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_npi.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_zh_CN.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
Labels: testing not required

#2712 SF-2951 Fix ProgressService not subscribing to chapter updates
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress-service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress-service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
Labels: bug, testing complete

#2677 SF-2919 Tweak UI for My Projects cards
  src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
Labels: testing complete

#2709 SF-2950 Fix authentication failure when joining a project with a link
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
Labels: bug, testing complete

#2717 Fix background color of notices on my projects page
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts
Labels: testing not required

#2719 SF-2974 Add highlight to selected step in material stepper
  src/SIL.XForge.Scripture/ClientApp/src/styles.scss
Labels: testing not required

#2711 SF-2958 Remove dependency on MediaObserver
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-breakpoint-observer.ts
Labels: will require testing

#2718 SF-2959 Remove fxShow and fxHide from component templates
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/delete-project-dialog/delete-project-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
Labels: testing not required

#2720 Find and group sync failures by cause
  mongodb/SyncMetrics/FindAndGroupSyncFailures.mongodb
Labels: testing not required

#2723 SF-2835 Add message for invalid markers in para USFM
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: ready to test

#2671 SF-2909 Biblical Terms Enhancements
  src/RealtimeServer/scriptureforge/models/editor-tab.ts
  src/RealtimeServer/scriptureforge/models/sf-project-user-config-test-data.ts
  src/RealtimeServer/scriptureforge/models/sf-project-user-config.ts
  src/RealtimeServer/scriptureforge/realtime-server.ts
  src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.spec.ts
  src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.ts
  src/RealtimeServer/scriptureforge/services/sf-project-user-config-service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/custom-icon.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/base-services/tab-menu.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/sf-tabs.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-header/tab-header.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-term-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-factory.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-factory.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/data-loading-component.ts
  src/SIL.XForge.Scripture/Models/SFProjectUserConfig.cs
Labels: testing complete

#2724 SF-2805 Only add source tabs if user can access the source
  src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: bug, ready to test

#2726 Fix checking app cut off on medium-sized viewport
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
Labels: testing not required

#2728 Rename services in ClientApp to follow convention
  src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/cache-service/cache.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/cache-service/cache.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/main.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/activated-project.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts
Labels: testing not required

#2731 SF-2966 Fix support for audio recording on iOS and Safari
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
Labels: testing not required

#2721 SF-2945 Add question record button to question icons
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
Labels: testing complete

#2736 Remove biblical terms tab top border
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.scss
Labels: testing not required

#2732 Minor test improvements for tab groups
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
Labels: testing not required

#2738 Move checking strings that were in the wrong file
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#2745 Add commit guidelines in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: testing not required

#2744 Switched to bullets for role description separators
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
Labels: testing not required

#2722 SF-2910 Add script to duplicate text audio docs in mongodb
  scripts/db_tools/duplicate-doc.js
  src/RealtimeServer/scriptureforge/models/text-audio.ts
  src/SIL.XForge.Scripture/Models/TextAudio.cs
Labels: testing not required

#2727 SF-2952 Fix resource tab not displaying right-to-left correctly
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-resource/editor-resource.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-resource/editor-resource.component.ts
Labels: ready to test

#2746 Add tracking of components using notice service
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts
Labels: testing not required

#2749 Update list of supported SIL fonts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/font.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/font.service.ts
  src/SIL.XForge.Scripture/fonts.json
Labels: testing not required

#2750 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_de.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_km.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_npi.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_zh_CN.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_de.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_km.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_npi.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_zh_CN.json
Labels: testing not required

#2740 SF-2998 Revert Biblical Terms migration
  src/RealtimeServer/scriptureforge/models/sf-project-user-config.ts
  src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.spec.ts
  src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.ts
  src/RealtimeServer/scriptureforge/services/sf-project-user-config-service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/Models/SFProjectUserConfig.cs
Labels: bug, Critical Path, testing not required

#2754 Fix SubscriptionDisposable subclasses failing to call ngOnDestroy
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts
Labels: testing not required
