Repository sillsdev/web-xforge, pull requests merged in 2024-01, with the labels that each got.

#2262 SF-2338 Update ngx-quill to v21.0.2
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts
Labels: testing not required

#2265 SF-2373 Upgrade legacy mat-snackbar
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/notice.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
Labels: testing not required

#2270 Add new transparent SF PNG
  src/SIL.XForge.Scripture/ClientApp/src/assets/images/sf.png
Labels: testing not required

#2271 SF-2433 Prevent error when joining a project with email specific link
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/activated-project.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/activated-project.service.ts
Labels: ready to test

#2273 SF-2432 Style editor height with CSS instead of JS
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing not required

#2268 SF-2334 Update to Angular 16
  src/RealtimeServer/package-lock.json
  src/RealtimeServer/package.json
  src/SIL.XForge.Scripture/ClientApp/.eslintrc.json
  src/SIL.XForge.Scripture/ClientApp/angular.json
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/delete-project-dialog/delete-project-dialog.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/project-router.guard.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-button.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.guard.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/mock-console.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-admin-auth.guard.ts
Labels: testing not required

#2269 Remove all use of letter spacing
  src/SIL.XForge.Scripture/ClientApp/src/_text.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
Labels: testing not required

#2267 SF-2370 Upgrade legacy mat-radio
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
Labels: testing not required

#2275 Fix broken migrator after Angular 16 upgrade
  src/RealtimeServer/package-lock.json
  src/RealtimeServer/package.json
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
Labels: testing not required

#2276 SF-2335b Remove @bugsnag/plugin-angular to fix Angular prod build
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
Labels: Critical Path, testing not required

#2279 Fix broken draft generation step tests
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
Labels: testing not required

#2281 Fix layout of editors when only one editor is shown
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
Labels: Critical Path, testing not required

#2251 SF-2410 Allow user selection of sending just verse segments or all segments
  src/RealtimeServer/scriptureforge/models/sf-project-test-data.ts
  src/RealtimeServer/scriptureforge/models/translate-config.ts
  src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts
  src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-settings.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
  src/SIL.XForge.Scripture/Models/DraftConfig.cs
  src/SIL.XForge.Scripture/Models/SFProjectSettings.cs
  src/SIL.XForge.Scripture/Services/PreTranslationService.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge.Scripture/Services/SFScriptureText.cs
  src/SIL.XForge.Scripture/Services/SFTextCorpusFactory.cs
  test/SIL.XForge.Scripture.Tests/Services/PreTranslationServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs
Labels: testing complete

#2278 SF-2438 Localize error message strings in chapter audio dialog
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
Labels: testing not required

#2283 SF-2450 Change text "Mark for export" to "Flag for review"
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#2284 SF-2368 Upgrade legacy mat-progress-bar
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/page-not-found/page-not-found.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
Labels: testing not required

#2288 Add Mongo query for comments created by sf_commenter role
  mongodb/Comments/find_commenters.mongodb
Labels: testing not required

#2285 SF-2347 Do not show error when getting project role times out
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts
Labels: testing not required

#2254 SF-2429 Allow creating quick translation draft builds
  scripts/db_tools/parse-version.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
  src/SIL.XForge.Scripture/Models/BuildConfig.cs
  src/SIL.XForge.Scripture/Services/BuildConfigJsonConverter.cs
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/BuildConfigJsonConverterTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
Labels: testing complete

#2289 Update notices over editor to use app-notice component
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing not required

#2274 SF-2434 Allow resolving note threads for biblical terms
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.ts
Labels: ready to test

#2282 SF-2449 Add verse ref to checking question list items
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
Labels: new feature, testing complete

#2293 SF-2384 Fix flicker after project book is deleted
  src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
Labels: ready to test

#2258 SF-2430 Make verse label consistent with highlighted verse
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
Labels: ready to test

#2286 SF-2310 Add Paratext zip file support for Serval
  scripts/db_tools/parse-version.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
  src/SIL.XForge.Scripture/Models/FeatureFlags.cs
  src/SIL.XForge.Scripture/Models/ServalCorpus.cs
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  src/SIL.XForge.Scripture/Services/PreTranslationService.cs
  src/SIL.XForge.Scripture/appsettings.json
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/PreTranslationServiceTests.cs
Labels: new feature, testing complete

#2295 FIX: Revert Target and Source flipped in SF-2432
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
Labels: fix recent change, testing not required

#2294 SF-2461 Restrict draft training books to canonical
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.ts
Labels: ready to test

#2297 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_zh_CN.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_zh_CN.json
  src/SIL.XForge.Scripture/Resources/Pages.Index.id.resx
  src/SIL.XForge.Scripture/Resources/SharedResource.id.resx
Labels: testing not required

#2300 SF-2463 Fix Paratext 7 Resources being marked as English
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: bug

#2298 SF-2462 Stop reporting pre-translation build in progress errors
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ServalApiExceptions.cs
Labels: bug, testing complete

#2234 SF-2390 Allow multiple roles per user
  src/RealtimeServer/common/connect-session.ts
  src/RealtimeServer/common/models/user-test-data.ts
  src/RealtimeServer/common/models/user.ts
  src/RealtimeServer/common/realtime-server.ts
  src/RealtimeServer/common/services/project-service.spec.ts
  src/RealtimeServer/common/services/project-service.ts
  src/RealtimeServer/common/services/user-migrations.spec.ts
  src/RealtimeServer/common/services/user-migrations.ts
  src/RealtimeServer/common/services/user-service.spec.ts
  src/RealtimeServer/common/services/user-service.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-admin-auth.guard.ts
  src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
  src/SIL.XForge.Scripture/Services/ISFProjectService.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge/Controllers/RpcControllerBase.cs
  src/SIL.XForge/Controllers/UsersRpcController.cs
  src/SIL.XForge/Models/User.cs
  src/SIL.XForge/Services/IProjectService.cs
  src/SIL.XForge/Services/IUserAccessor.cs
  src/SIL.XForge/Services/IUserService.cs
  src/SIL.XForge/Services/ProjectService.cs
  src/SIL.XForge/Services/UserAccessor.cs
  src/SIL.XForge/Services/UserService.cs
  test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsRpcControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
  test/SIL.XForge.Tests/Controllers/UsersRpcControllerTests.cs
  test/SIL.XForge.Tests/Services/ProjectServiceTests.cs
  test/SIL.XForge.Tests/Services/UserAccessorTests.cs
  test/SIL.XForge.Tests/Services/UserServiceTests.cs
Labels: testing complete

#2306 Update error reporting messages to not say reports are public
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#2307 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_zh_CN.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_zh_CN.json
Labels: testing not required

#2305 SF-2470 Fix incorrect books sent to Serval for Pre-Translation
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
Labels: bug, Critical Path, ready to test

#2309 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
Labels: testing not required

#2250 SF-2405 Improve AudioPlayer loading of short audio files in Chromium
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/test-audio/test-audio-short.mp3
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts
  src/SIL.XForge.Scripture/ClientApp/src/karma.conf.js
Labels: testing complete

#2301 Improve question import speed when questions have already been imported
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
Labels: testing not required

#1764 SF-1444 Preserve important whitespace when get text
  .vscode/launch.json
  .vscode/tasks.json
  scripts/db_tools/manage-db.ts
  scripts/db_tools/trigger-resources-need-sync.ts
  src/Migrations/WhitespaceRestoreMigration/Migrator.cs
  src/Migrations/WhitespaceRestoreMigration/Program.cs
  src/Migrations/WhitespaceRestoreMigration/Properties/launchSettings.json
  src/Migrations/WhitespaceRestoreMigration/Startup.cs
  src/Migrations/WhitespaceRestoreMigration/WhitespaceRestoreMigration.csproj
  src/Migrations/WhitespaceRestoreMigration/WhitespaceRestoreMigration.sln
  src/Migrations/WhitespaceRestoreMigration/build-production
  src/Migrations/WhitespaceRestoreMigration/process-by-chunk
  src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: will require testing

#2304 SF-2469 Inform user when no mic is found
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
Labels: testing complete

#2296 SF-2371 Update from Material legacy form related controls
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comment-form/checking-comment-form.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/history-chooser/history-chooser.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
Labels: testing complete

#2266 SF-2372 Upgrade legacy mat-slide-toggle
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
Labels: testing not required

#2318 Show project short name on system admin projects page
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.ts
Labels: testing not required

#2313 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_zh_CN.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
Labels: testing not required

#2319 SF-2479 Restrict scope of lock to token refresh
  src/SIL.XForge.Scripture/Services/ParatextService.cs
Labels: testing complete

#2314 Introduce ChapterDelta and USX roundtripping tests
  src/SIL.XForge.Scripture/Models/Chapter.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/SampleData/heb_usfm.zip
  test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: testing not required
