Repository sillsdev/web-xforge, pull requests merged in 2024-12, with the labels that each got.

#2877 SF-3100 Move to next question when previous question is archived
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
Labels: ready to test

#2871 SF-3078 Prompt user for microphone access before recorder countdown
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts
Labels: ready to test

#2879 Remove unneeded this from template files
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-information/draft-information.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.html
Labels: testing not required

#2878 Dependency Security Updates
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge/SIL.XForge.csproj
  test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
  test/SIL.XForge.Scripture.Tests/Services/FileSystemServiceTests.cs
  test/SIL.XForge.Tests/SIL.XForge.Tests.csproj
Labels: testing not required

#2882 Update error page news link
  src/SIL.XForge.Scripture/ErrorPages/503.html
Labels: testing not required

#2866 Add script and workflow to fetch translations from Crowdin
  .github/workflows/update-localizations.yml
  scripts/update_from_crowdin.mts
Labels: testing not required

#2880 SF-3097 Set WritingSystem Region and Script
  src/RealtimeServer/common/models/writing-system.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.ts
  src/SIL.XForge.Scripture/Models/ParatextProject.cs
  src/SIL.XForge.Scripture/Models/ParatextSettings.cs
  src/SIL.XForge.Scripture/Services/IParatextService.cs
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge/Models/WritingSystem.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: testing not required

#2885 Fix support for Windows on ARM64
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
Labels: testing not required

#2873 SF-3095 Fix sync progress display when loading a resource.
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.html
Labels: testing complete

#2889 Update query for active translate projects
  mongodb/Projects/ActiveTranslateProjects.mongodb
Labels: testing not required

#2730 SF-2986 Add step to confirm language codes before generating draft
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: new feature, testing complete

#2865 SF-3093 Allow adding draft to a book when project plans are used
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: testing complete

#2881 SF-3088 Queue getWordGraph API calls
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts
Labels: testing complete

#2887 Add support for showing timezone in date format
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
Labels: testing not required

#2888 Add global notices component with upcoming downtime message
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/global-notices/global-notices.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/global-notices/global-notices.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/global-notices/global-notices.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/global-notices/global-notices.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
Labels: testing not required

#2890 Remove unused private members from TypeScript files
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts
Labels: testing not required

#2891 Fix broken unit tests
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
Labels: testing not required

#2899 Improve draft generation enumeration of unselectable books
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
Labels: testing not required

#2902 Hide learning rate notice after 60 days
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
Labels: testing not required

#2904 Sort imports on all TypeScript files
  .vscode/settings.json
  src/RealtimeServer/common/services/user-service.spec.ts
  src/RealtimeServer/common/services/user-service.ts
  src/RealtimeServer/scriptureforge/models/biblical-term.ts
  src/RealtimeServer/scriptureforge/models/note-thread.ts
  src/RealtimeServer/scriptureforge/models/question.ts
  src/RealtimeServer/scriptureforge/models/training-data.ts
  src/RealtimeServer/scriptureforge/services/biblical-term-service.spec.ts
  src/RealtimeServer/scriptureforge/services/biblical-term-service.ts
  src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts
  src/RealtimeServer/scriptureforge/services/note-thread-service.ts
  src/RealtimeServer/scriptureforge/services/question-service.spec.ts
  src/RealtimeServer/scriptureforge/services/question-service.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.spec.ts
  src/RealtimeServer/scriptureforge/services/text-audio-service.spec.ts
  src/RealtimeServer/scriptureforge/services/text-audio-service.ts
  src/RealtimeServer/scriptureforge/services/text-service.ts
  src/RealtimeServer/scriptureforge/services/training-data-service.spec.ts
  src/RealtimeServer/scriptureforge/services/training-data-service.ts
  src/SIL.XForge.Scripture/ClientApp/.storybook/util/mat-dialog-launch.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app-routing.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-confirmation-dialog/import-question-confirmation-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-confirmation-dialog/import-question-confirmation-dialog.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/biblical-term-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-audio-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/training-data-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/translation-engine.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/delete-project-dialog/delete-project-dialog.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/project-router.guard.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-term-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-factory.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flags-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n-story.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/user-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/user-profile-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-online-status.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/xforge-common.module.ts
Labels: testing not required

#2893 SF-3108 Do not allow generating drafts in draft wizard when offline
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
Labels: testing not required

#2908 Use site-specific 503 error page
  src/SIL.XForge.Scripture/ErrorPages/503-generic.html
  src/SIL.XForge.Scripture/ErrorPages/503-sf.html
Labels: testing not required

#2906 Make projectToDraftSources from ConfirmSourcesComponent a util function
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts
Labels: testing not required

#2898 SF-3082 Remove persisted resource tabs from deleted projects
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: bug, testing complete

#2892 SF-3086 Fix Checking Overview Not Updating for Bulk Import
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-realtime.service.ts
Labels: testing complete

#2907 Add workflow to scan workflows with zizmor
  .github/workflows/zizmor.yml
  .vscode/settings.json
Labels: testing not required

#2910 Link to localized sharing help when it is available
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.ts
Labels: testing not required

#2825 SF-2900 Mixed Source: Selecting books from each source
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/build-dto.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-information/draft-information.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/Models/BuildConfig.cs
  src/SIL.XForge.Scripture/Models/DraftConfig.cs
  src/SIL.XForge.Scripture/Models/MachineApi.cs
  src/SIL.XForge.Scripture/Models/ProjectScriptureRange.cs
  src/SIL.XForge.Scripture/Models/ServalAdditionalTrainingData.cs
  src/SIL.XForge.Scripture/Models/ServalBuildAdditionalInfo.cs
  src/SIL.XForge.Scripture/Models/ServalCorpus.cs
  src/SIL.XForge.Scripture/Models/ServalCorpusFile.cs
  src/SIL.XForge.Scripture/Models/ServalCorpusSync.cs
  src/SIL.XForge.Scripture/Models/ServalData.cs
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/Services/BuildConfigJsonConverter.cs
  src/SIL.XForge.Scripture/Services/IMachineProjectService.cs
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  src/SIL.XForge.Scripture/Services/MachineServiceCollectionExtensions.cs
  src/SIL.XForge.Scripture/Services/PreTranslationService.cs
  src/SIL.XForge.Scripture/Services/SFBiblicalTermsText.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge/Utils/StringUtils.cs
  test/SIL.XForge.Scripture.Tests/Services/BuildConfigJsonConverterTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MockText.cs
  test/SIL.XForge.Scripture.Tests/Services/PreTranslationServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFBiblicalTermsTextTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
  tools/ServalBuildReport/Program.cs
  tools/ServalBuildReport/ServalBuildReport.csproj
  tools/ServalDownloader/Program.cs
  tools/ServalDownloader/ServalDownloader.csproj
Labels: ready to test

#2913 Update .git-blame-ignore-revs with the most recent CSharpier commit
  .git-blame-ignore-revs
Labels: testing not required

#2916 Verify migrations have monotonically increasing version numbers
  src/RealtimeServer/common/migration.ts
  src/RealtimeServer/common/services/user-migrations.ts
  src/RealtimeServer/scriptureforge/services/biblical-term-migrations.ts
  src/RealtimeServer/scriptureforge/services/note-thread-migrations.ts
  src/RealtimeServer/scriptureforge/services/question-migrations.ts
  src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts
  src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.ts
  src/RealtimeServer/scriptureforge/services/text-audio-migrations.ts
  src/RealtimeServer/scriptureforge/services/text-migrations.ts
  src/RealtimeServer/scriptureforge/services/training-data-migrations.ts
Labels: testing not required

#2920 SF-3121 Upgrade old subscribe calls to use observers
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/subscription-disposable.ts
Labels: testing not required

#2919 SF-3122 Use lambda in all throwError calls
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts
Labels: testing not required

#2905 SF-3114 Make chapter audio only hide bottom bar if scripture text is shown
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
Labels: ready to test

#2875 SF-3077 Add UI for mixed training sources
  src/RealtimeServer/scriptureforge/models/translate-config.ts
  src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts
  src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#2901 SF-3026 Force consistent date format for Nepali across platforms
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
Labels: testing complete

#2918 SF-3120 Replace toPromise with lastValueFrom
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/page-not-found/page-not-found.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/retrying-request.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/testing-retrying-request.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts
Labels: ready to test

#2911 SF-3070 Refresh the selected verse if the states are wrong
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: ready to test

#2900 SF-3068 Improve Biblical Terms Tab when offline
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#2917 SF-3123 Update ParatextData to 9.5.0.8
  src/Migrations/BackoutCommits/BackoutCommits.csproj
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/Services/NotesFormatter.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  tools/CommentGenerator/CommentGenerator.csproj
  tools/RepoInfo/RepoInfo.csproj
Labels: testing complete

#2926 Fix shadow on question count card
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
Labels: testing not required
