Repository sillsdev/web-xforge, pull requests merged in 2024-02, with the labels that each got.

#2316 SF-2477 Menus do not automatically close when opening another menu
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
Labels: testing complete

#2310 SF-2466 Remove warnings against selecting training data for NLLB languages
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#2323 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_zh_CN.json
Labels: testing not required

#2312 SF-2355 Translation Suggestions don't align well in RTL
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.ts
Labels: testing complete

#2321 SF-2474 Set selectedTask when navigating to Manage Questions
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
Labels: testing complete

#2311 SF-1363 Cursor in translate tool follows cursor in another browser window and causes glitchy behavior
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing complete

#2331 Show all project short names on system admin projects page
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.html
Labels: testing not required

#2315 SF-2478 Support nb paragraph marker
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
  src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
  test/SIL.XForge.Scripture.Tests/SampleData/eng-asv_usfm-partial.zip
  test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
Labels: testing complete

#2320 SF-2486 Show the correct username for notes created in Paratext
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
  src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
Labels: testing complete

#2327 SF-2496 Move "add chapter audio" to chapter menu on questions dashboard
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
Labels: testing complete

#2337 Add query to find sync errors for a project
  mongodb/Projects/SyncFailureCause.mongodb
Labels: testing not required

#2336 Remove note thread update logs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
Labels: testing not required

#2325 SF-2437 Restrict audio upload to 95MB
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/project-data-doc.ts
  src/SIL.XForge.Scripture/Controllers/SFProjectsUploadController.cs
Labels: ready to test

#2322 SF-1581 No error on empty email field when sending invite
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts
Labels: testing complete

#2340 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_zh_CN.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
Labels: testing not required

#2338 SF-2524 Prevent applying drafts when editing is not permitted
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts
Labels: testing complete

#2329 SF-2498 Fix crash when no access to source project
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#2326 SF-2493 Fix training source language for back translations
  src/SIL.XForge.Scripture/Services/IMachineProjectService.cs
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: testing complete

#2345 SF-2550 Disable In-Process Machine across all environments
  src/SIL.XForge.Scripture/appsettings.json
Labels: testing not required

#2351 Downgrade Jering to 6.3.1
  src/SIL.XForge/Realtime/ExistingNodeJSProcess.cs
  src/SIL.XForge/Realtime/ExistingNodeJSProcessFactory.cs
  src/SIL.XForge/Realtime/RealtimeServer.cs
  src/SIL.XForge/Realtime/RealtimeServiceCollectionExtensions.cs
  src/SIL.XForge/SIL.XForge.csproj
Labels: testing not required

#2349 SF-2568 Allow all PT users to view chapter history
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: testing complete

#2344 SF-2563 Fix issues with Serval Alternate Training Sources
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
Labels: bug, testing complete

#2339 SF-2485 Handle table followed by char formatting
  src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
  src/SIL.XForge/Realtime/RichText/Delta.cs
  test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
  test/SIL.XForge.Scripture.Tests/Services/DeltaUsxTestExtensions.cs
Labels: ready to test

#2343 SF-1622 Restart Realtime Server
  src/RealtimeServer/common/index.ts
  src/SIL.XForge/Realtime/DeleteOnSuccessAttribute.cs
  src/SIL.XForge/Realtime/IRealtimeServer.cs
  src/SIL.XForge/Realtime/RealtimeServer.cs
  src/SIL.XForge/Realtime/RealtimeService.cs
  test/SIL.XForge.Tests/Realtime/ConnectionTests.cs
  test/SIL.XForge.Tests/Realtime/RealtimeServiceTests.cs
Labels: testing not required

#2347 SF-2551 Throttle Syncs to one at a time
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  src/SIL.XForge.Scripture/Services/MutexAttribute.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
Labels: testing complete

#2353 SF-1588 Suggestions settings also requires general edit permission
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: bug, testing complete

#2335 SF-2499 Add quick buttons for selecting books when drafting
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#2352 Add tool to download all files from Serval
  tools/ServalDownloader/Program.cs
  tools/ServalDownloader/ServalDownloader.csproj
  tools/ServalDownloader/ServalDownloader.sln
  tools/ServalDownloader/appsettings.json
Labels: .NET, testing not required

#2342 SF-2464 Use Serval to check whether a language code is supported
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_zh_CN.json
  src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
  src/SIL.XForge.Scripture/Models/LanguageDto.cs
  src/SIL.XForge.Scripture/Models/MachineApi.cs
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/Services/IMachineApiService.cs
  src/SIL.XForge.Scripture/Services/IMachineProjectService.cs
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  src/SIL.XForge.Scripture/Services/MachineServiceCollectionExtensions.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
Labels: testing complete

#2355 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_zh_CN.json
  src/SIL.XForge.Scripture/Resources/Pages.LearnMore.id.resx
Labels: testing not required

#2354 Pass client ID to auth0 when changing password
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth0.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth0.service.ts
Labels: testing not required

#2238 SF-2395 Make Mobile Great Again
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.scss
Labels: ready to test

#2357 SF-2582 Improve recoverability when Serval client credentials change
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts
  src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
Labels: bug, will require testing

#2334 SF-2527 Support for invalid reattached notes
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: bug, ready to test
