Repository sillsdev/web-xforge, pull requests merged in 2024-08, with the labels that each got.

#2641 Make roles message on users page clearer
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#2644 Fix tests with missing expectations and import typos
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
Labels: testing not required

#2624 SF-2876 Link logo on my projects page to previous project
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
Labels: testing complete

#2639 SF-2877 Show correct date format for history tab
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing complete

#2596 SF-2749 Refactor scrolling to active verse
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
Labels: testing complete

#2647 Add query to find projects that are using a given project as a source
  mongodb/Projects/FindProjectsUsingProjectAsSource.mongodb
Labels: testing not required

#2579 SF-2833 Use Source USFM for pre-translation drafts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/Services/PreTranslationService.cs
  test/SIL.XForge.Scripture.Tests/Services/PreTranslationServiceTests.cs
Labels: testing complete

#2600 SF-2862 Get source project language from the active source for serval
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
Labels: testing complete

#2646 SF-2858 Fix position of unread count icon in RTL
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html
Labels: testing complete

#2637 SF-2892 Fix error when Serval admin enables drafting
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
Labels: ready to test

#2642 Add Mongo query to find common sync failure reasons
  mongodb/SyncMetrics/FindCommonSyncFailureReasons.mongodb
  mongodb/SyncMetrics/FindCurrentSyncErrors.mongodb
Labels: testing not required

#2585 Change "user edit counts" report to group data by year, then month, then user, then chapter
  scripts/db_tools/report-user-edits.ts
Labels: enhancement, testing not required

#2564 SF-2822 Create 'user comment count' report script
  scripts/db_tools/report-user-comments.ts
Labels: testing not required

#2649 Update sync status query to make order of states consistent
  mongodb/SyncMetrics/SyncStatusOverTime.mongodb
Labels: testing not required

#2650 Update Mongo query to filter for only recent failure causes
  mongodb/SyncMetrics/FindCommonSyncFailureReasons.mongodb
Labels: testing not required

#2652 Improve cancel draft wording
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#2655 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_de.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_npi.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_zh_CN.json
Labels: testing not required

#2654 Improve layout of notice on feature flag dialog
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flags-dialog.component.scss
Labels: testing not required

#2656 Change Synchronize to Sync with Paratext
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#2651 SF-2880 Note icon not appearing after navigating from Users page
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing complete

#2638 SF-2893 Remove RecordRTC
  src/SIL.XForge.Scripture/ClientApp/angular.json
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/typings/recordrtc.d.ts
Labels: testing complete

#2645 SF-2891 Upgrade to Angular Material 17
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/font-size/font-size.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-multi-select.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
Labels: testing complete

#2657 SF-2866 Update the avatar icon after the user's name changes
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.ts
Labels: testing complete

#2658 SF-2604 Update history tab when the language changes
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/editor-history.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/editor-history.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-revision-format.pipe.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing complete

#2663 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_de.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_npi.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_zh_CN.json
Labels: testing not required

#2659 Fix the notes dialog title for Study Bible footnotes
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-note-dialog/text-note-dialog.component.ts
Labels: testing not required

#2635 SF-2516 Remove project selector from connect project page
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#2664 Clean up migration to template control flow syntax
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/scripture-chooser-dialog/scripture-chooser-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player/audio-player.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-button.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-term-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-upload-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/editor-history.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/training-progress/training-progress.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/generic-dialog/generic-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/write-status/write-status.component.html
Labels: testing not required

#2665 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_de.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_npi.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_zh_CN.json
Labels: testing not required

#2666 Remove unneeded trailing padding from nav menu items
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.scss
Labels: testing not required

#2661 Merge Material dialog storybook launchers
  src/SIL.XForge.Scripture/ClientApp/.storybook/story-utils.ts
  src/SIL.XForge.Scripture/ClientApp/.storybook/util/mat-dialog-launch.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-confirmation-dialog/import-question-confirmation-dialog.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/delete-project-dialog/delete-project-dialog.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/supported-browsers-dialog/supported-browsers-dialog.stories.ts
Labels: testing not required

#2653 SF-2867 Allow moving backwards via verse with SF note using left arrow
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
Labels: testing complete

#2640 SF-2835 Add message for unsupported USFM
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
Labels: testing complete

#2668 SF-2907 Remove linting from build and test workflow
  .github/workflows/build-and-test.yml
  .github/workflows/ci-lint-prettier.yml
Labels: testing not required

#2614 SF-2865 Fix autodraft open on nav when mobile view with source
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-group.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-group.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: bug, ready to test

#2662 SF-2906 Fix crash when syncing and notes with duplicate ids are incoming
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: bug, testing complete

#2648 deploy: add more details on build_commit being used
  .github/workflows/compute-next-version.yml
  .github/workflows/release-live.yml
  .github/workflows/release-qa.yml
Labels: testing not required

#2672 SF-2916 Change display name label on join component
  src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.spec.ts
Labels: testing not required

#2660 SF-2905 Fix crash when syncing a book with invalid chapters
  src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
  test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
Labels: bug, testing complete

#2678 Add support for SIL TTF fonts
  scripts/update_font_list.mts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/font.service.ts
  src/SIL.XForge.Scripture/fonts.json
Labels: testing not required

#2674 SF-2926 Allow viewing history if Paratext sync directory is missing
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: testing complete

#2675 SF-2927 Fix incorrect escaping of XML characters in notes
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.ts
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: Critical Path, testing not required

#2673 SF-2918 Create extract project script for Windows and Linux
  scripts/extract-project.bat
  scripts/extract-project.sh
Labels: testing not required

#2670 SF-2901 Display completion status via new ProgressService
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress-service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress-service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/data-loading-component.ts
Labels: testing complete

#2681 Add draft configuration information to Serval admin page
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
Labels: testing not required

#2669 SF-2908 Fix crash when syncing specific Paratext Resources
  src/SIL.XForge.Scripture/Services/ParatextService.cs
Labels: bug, testing complete

#2683 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_de.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_npi.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_zh_CN.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_de.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_npi.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_zh_CN.json
Labels: testing not required

#2682 Fix annoying MatTooltip
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
Labels: testing not required

#2676 SF-2894 Create new record dialog
  src/SIL.XForge.Scripture/ClientApp/.storybook/util/mat-dialog-launch.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
Labels: testing not required

#2686 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_de.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_de.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
  src/SIL.XForge.Scripture/Resources/Pages.LearnMore.de.resx
  src/SIL.XForge.Scripture/Resources/SharedResource.de.resx
Labels: testing not required

#2687 SF-2936 Show diagnostic information to serval admins
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-information/draft-information.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-information/draft-information.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-information/draft-information.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-information/draft-information.component.ts
Labels: testing not required

#2688 Fix padding of offline message on users page
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.html
Labels: testing not required

#2621 SF-2860 Users notified when offline on My Projects page
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user-projects.service.ts
Labels: ready to test

#2685 SF-2937 Fix uploading of training data files
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-multi-select.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-multi-select.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-multi-select.component.ts
Labels: bug, testing complete

#2692 SF-2915 Fix crash when retrieving Paratext tokens for deleted users
  src/SIL.XForge/Services/AuthService.cs
  test/SIL.XForge.Tests/Services/AuthServiceTests.cs
  test/SIL.XForge.Tests/Services/MockHttpMessageHandler.cs
Labels: testing not required
