Repository sillsdev/web-xforge, pull requests merged in 2024-07, with the labels that each got.

#2563 SF-2824 Fix build-and-ship script
  scripts/build-and-ship
Labels: Critical Path

#2565 Fix realtime server origin on QA
  scripts/build-and-ship
Labels: testing not required

#2520 SF-2780 Correctly parse pre-translation references with slashes
  src/SIL.XForge.Scripture/Services/PreTranslationService.cs
  test/SIL.XForge.Scripture.Tests/Services/PreTranslationServiceTests.cs
Labels: testing complete

#2532 SF-2797 Add editor tab header tooltips
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/sf-tabs-config.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/sf-tabs.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-header/tab-header.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-header/tab-header.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-header/tab-header.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab/tab.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/editor-history.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-request.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-request.service.ts
Labels: new feature, testing complete

#2562 Remove Legacy Codecov Uploader
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
Labels: testing not required

#2566 Simplify history chooser styles
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.scss
Labels: testing not required

#2567 Fix duplicate add-question-button ID on checking overview
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
Labels: testing not required

#2561 Add .git-blame-ignore-revs file
  .git-blame-ignore-revs
Labels: testing not required

#2531 Add index to sf_project_secrets.shareKeys.key
  src/SIL.XForge.Scripture/DataAccess/SFDataAccessServiceCollectionExtensions.cs
Labels: testing not required

#2529 SF-2788 Reduce calls to the Paratext Registry
  src/SIL.XForge.Scripture/Models/ParatextProjectUser.cs
  src/SIL.XForge.Scripture/Services/IInternetSharedRepositorySource.cs
  src/SIL.XForge.Scripture/Services/IParatextNotesMapper.cs
  src/SIL.XForge.Scripture/Services/IParatextService.cs
  src/SIL.XForge.Scripture/Services/ISFProjectService.cs
  src/SIL.XForge.Scripture/Services/JwtInternetSharedRepositorySource.cs
  src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextNotesMapperTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: testing complete

#2570 Hide share expiration radio button
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.html
Labels: testing not required

#2548 SF-2640 Warn when font unsupported
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/font.service.ts
Labels: testing complete

#2568 SF-2825 Place Additional Training Source behind a Feature Flag
  scripts/db_tools/parse-version.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
Labels: testing complete

#2558 SF-2810 Add tooltips to CC answers
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#2560 SF-2823 Improve user-edit-counts script
  scripts/db_tools/report-user-edits.ts
Labels: testing complete

#2574 Change the history restore icon to "undo"
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.html
Labels: testing not required

#2577 Add query to find project given engine ID
  mongodb/Projects/FindProjectFromEngineId.mongodb
Labels: testing not required

#2572 SF-2768 Join component supresses unknown errors
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
Labels: testing complete

#2573 SF-2828 Remove the delete user button on self on system admin page
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.ts
Labels: ready to test

#2569 SF-2830 Optimise the syncing of notes to Paratext
  src/SIL.XForge.Scripture/Services/IParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: testing complete

#2544 SF-2742 Fix syncing of projects by newly added administrators
  src/SIL.XForge.Scripture/Models/ParatextRegistryPermissionManager.cs
  src/SIL.XForge.Scripture/Services/ISharingLogicWrapper.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/SharingLogicWrapper.cs
  test/SIL.XForge.Scripture.Tests/Services/ComparableProjectPermissionManager.cs
  test/SIL.XForge.Scripture.Tests/Services/MockScrText.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: testing complete

#2575 SF-2711 Do not display sync complete before ops are written to Mongo
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: testing complete

#2556 SF-2802 Make it possible to revert to the draft as it was originally created
  src/RealtimeServer/common/index.ts
  src/RealtimeServer/common/realtime-server.ts
  src/RealtimeServer/common/utils/sharedb-utils.ts
  src/RealtimeServer/common/utils/test-utils.ts
  src/RealtimeServer/scriptureforge/services/text-service.spec.ts
  src/RealtimeServer/typings/sharedb/index.d.ts
  src/RealtimeServer/typings/sharedb/lib/client.d.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/text-doc.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/text-doc.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/editor-history.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-revision-format.pipe.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/typings/sharedb.d.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-realtime-remote-store.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime-remote-store.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts
  src/SIL.XForge.Scripture/Controllers/ParatextController.cs
  src/SIL.XForge.Scripture/Models/DocumentRevision.cs
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/Services/ApiDocumentationExtensions.cs
  src/SIL.XForge.Scripture/Services/IParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  src/SIL.XForge/Models/QueuedOperation.cs
  src/SIL.XForge/Realtime/Connection.cs
  src/SIL.XForge/Realtime/Document.cs
  src/SIL.XForge/Realtime/IConnection.cs
  src/SIL.XForge/Realtime/IDocument.cs
  src/SIL.XForge/Realtime/IRealtimeServer.cs
  src/SIL.XForge/Realtime/Json0/Json0Extensions.cs
  src/SIL.XForge/Realtime/MemoryConnection.cs
  src/SIL.XForge/Realtime/MemoryDocument.cs
  src/SIL.XForge/Realtime/OpMetadata.cs
  src/SIL.XForge/Realtime/OpSource.cs
  src/SIL.XForge/Realtime/RealtimeServer.cs
  test/SIL.XForge.Scripture.Tests/Controllers/ParatextControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Tests/Realtime/ConnectionTests.cs
Labels: testing complete

#2584 SF-2831 Null check for remote changes
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing complete

#2580 SF-2827 Require share link language selection
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
Labels: testing complete

#2571 SF-2617 Add ability to add a draft by book
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-add-dialog/draft-add-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-add-dialog/draft-add-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-add-dialog/draft-add-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-add-dialog/draft-add-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: new feature, ready to test

#2588 SF-2747 Update question refs and donut summary when archiving last visible question
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
Labels: bug, testing complete

#2590 Update projects query to better count real projects
  mongodb/Projects/ProjectsOverTime.mongodb
Labels: testing not required

#2591 Default autofocus in dialogs to false
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/delete-project-dialog/delete-project-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-button.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-request.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/type-utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/edit-name-dialog/edit-name-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling-service.ts
Labels: testing not required

#2328 SF-2508 Introduce My Projects page
  src/RealtimeServer/common/models/user.ts
  src/RealtimeServer/scriptureforge/models/sf-project.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app-routing.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation-project-selector/navigation-project-selector.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation-project-selector/navigation-project-selector.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation-project-selector/navigation-project-selector.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation-project-selector/navigation-project-selector.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/page-not-found/page-not-found.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/start/start.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/router-link.directive.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user-projects.service.ts
Labels: testing complete

#2557 SF-2687 Remove global styles for checkboxes
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flags-dialog.component.scss
Labels: testing complete

#2593 SF-2851 Update source id when tab groups consolidate
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing complete

#2581 SF-2692 Fix warning messages for translators on the generate draft page
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#2592 SF-2849 Skip getting draft build when project is a resource
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.ts
Labels: ready to test

#2587 SF-2691 Fixed manage audio button not displaying for non-admin users
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
Labels: ready to test

#2597 Using default port when starting angular in dev env
  src/SIL.XForge.Scripture/Startup.cs
Labels: testing not required

#2599 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_zh_CN.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_zh_CN.json
Labels: testing not required

#2598 SF-2839 Align draft download spinner with other content
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
Labels: testing not required

#2601 SF-2865 Fix nav to open 'Auto Draft' tab from draft gen
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.ts
Labels: bug, ready to test

#2609 hotfix: SF-2865 Fix nav to open 'Auto Draft' tab from draft gen (#2601)
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.ts
Labels: testing not required

#2583 Add Serval Build Report Generator
  tools/ServalBuildReport/Program.cs
  tools/ServalBuildReport/README.md
  tools/ServalBuildReport/ServalBuildReport.csproj
  tools/ServalBuildReport/ServalBuildReport.sln
  tools/ServalBuildReport/appsettings.json
Labels: testing not required

#2608 SF-2868 Fix sidenav incorrect focus on mobile
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
Labels: ready to test

#2535 Add Deploy GitHub workflows
  .github/workflows/compute-next-version.py
  .github/workflows/compute-next-version.yml
  .github/workflows/release-live.yml
  .github/workflows/release-qa.yml
  .github/workflows/release-to-qa.yml
  .github/workflows/release.yml
Labels: testing not required

#2619 deploy: use defined credentials
  scripts/build-and-ship
Labels: testing not required

#2612 SF-2873 Show "Draft in progress" above "Preview last draft"
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
Labels: ready to test

#2607 SF-2872 Add icons to help menu
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
Labels: testing complete

#2602 SF-2870 Improve layout on my projects page
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.stories.ts
Labels: testing complete

#2610 SF-2741 Delete project on server before deleting serval project
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: .NET, testing complete

#2615 Add query to measure sync success rate over time
  mongodb/SyncMetrics/SyncStatusOverTime.mongodb
Labels: testing not required

#2620 deploy: fix and enhance release workflow process
  .github/workflows/compute-next-version.py
  .github/workflows/compute-next-version.yml
  .github/workflows/release-live.yml
  .github/workflows/release-qa.yml
  .github/workflows/release.yml
Labels: testing not required

#2611 SF-2842 Improve font unsupported notice
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
Labels: testing complete

#2623 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_zh_CN.json
Labels: testing not required

#2603 SF-2783 Use a specific error message when PT registry is not responding
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/Controllers/ParatextController.cs
  test/SIL.XForge.Scripture.Tests/Controllers/ParatextControllerTests.cs
Labels: testing not required

#2628 SF-2887 Update announcements link
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.ts
Labels: ready to test

#2629 SF-2890 Add German localization
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_de.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_de.json
  src/SIL.XForge.Scripture/Resources/Pages.Index.de.resx
  src/SIL.XForge.Scripture/Resources/Pages.LearnMore.de.resx
  src/SIL.XForge.Scripture/Resources/SharedResource.de.resx
  src/SIL.XForge.Scripture/locales.json
Labels: testing not required

#2633 Retry npm ci in workflows when it fails
  .github/workflows/build-and-test.yml
  .github/workflows/chromatic.yml
  .github/workflows/ci-lint-prettier.yml
  .github/workflows/ci-production-build.yml
Labels: testing not required

#2626 SF-2884 Fix sync problem when a note has no content
  src/SIL.XForge.Scripture/Models/Note.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: testing not required

#2634 Sort locales by usage
  mongodb/Users/SortLocalesByUsage.mongodb
  src/SIL.XForge.Scripture/locales.json
Labels: testing not required

#2604 SF-2874 Improve draft preview books appearance and implementation
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.scss
Labels: testing complete

#2613 SF-2859 Inform user when the share link problem is known
  src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/join/join.component.ts
Labels: testing complete

#2636 hotfix: SF-2884 Fix sync problem when a note has no content
  src/SIL.XForge.Scripture/Models/Note.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: testing not required

#2497 Add Nepali locale and localizations
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_npi.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_npi.json
  src/SIL.XForge.Scripture/Resources/Pages.LearnMore.npi.resx
  src/SIL.XForge.Scripture/Resources/SharedResource.npi.resx
  src/SIL.XForge.Scripture/locales.json
Labels: testing not required

#2643 Update all translation files from Crowdin
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ar.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_az.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_es.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_fr.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_id.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_kyu.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_lo.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_npi.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_pt_BR.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ro.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_ru.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_zh_CN.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_de.json
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_npi.json
Labels: testing not required
