Repository sillsdev/web-xforge, pull requests merged in 2025-06, with the labels that each got.

#3233 SF-3411 Fix crash when a scripture range is missing
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
Labels: testing not required

#3234 SF-3219b Remove draft improvement notice
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#3239 SF-3414 Show language tags on Serval admin page
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
Labels: testing not required

#3230 SF-3406 Improve lynx problems panel performance
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#3229 SF-3400 Show draft history in descending order
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
Labels: ready to test

#3242 SF-3415 Add sync and connect endpoints to the paratext-api
  src/SIL.XForge.Scripture/Controllers/ParatextController.cs
  src/SIL.XForge.Scripture/Models/SFProjectCreateSettings.cs
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge.Scripture/packages.lock.json
  test/SIL.XForge.Scripture.Tests/Controllers/ParatextControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: testing not required

#3254 Fix Storybook avatar tests failing due to missing image
  src/SIL.XForge.Scripture/ClientApp/src/data-uris.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.stories.ts
Labels: testing not required

#3248 SF-3390 Show book names in summarized format in draft history
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
Labels: testing complete

#3228 SF-3405 Allow selecting mid-verse paragraph break options
  src/RealtimeServer/scriptureforge/models/translate-config.ts
  src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts
  src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-usfm-format/draft-usfm-format.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-usfm-format/draft-usfm-format.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-usfm-format/draft-usfm-format.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-usfm-format/draft-usfm-format.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
  src/SIL.XForge.Scripture/Models/DraftUsfmConfig.cs
  src/SIL.XForge.Scripture/Services/PreTranslationService.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/PreTranslationServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: testing complete

#3223 SF-3322 Allow selecting book and chapter in community checking
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
Labels: testing complete

#3256 SF-2996 Warn on unused private class members and fix current warnings
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel-header/lynx-insights-panel-header.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-realtime-remote-store.ts
  src/SIL.XForge.Scripture/ClientApp/tsconfig.json
Labels: testing not required

#3255 Deduplicate date format function for file names
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts
Labels: testing not required

#3266 SF-3343 Fix error when use refreshes configure source page while offline
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
Labels: ready to test

#3270 Increase the sync timeout in e2e tests to two minutes
  src/SIL.XForge.Scripture/ClientApp/e2e/e2e-globals.ts
Labels: testing not required

#3268 SF-3428 Fix error when selecting all books scope when no question selected
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
Labels: critical path, testing complete

#3274 Remove UntypedFormControl from import questions dialog
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
Labels: testing not required

#3276 Enable Swagger on QA
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/Startup.cs
  src/SIL.XForge.Scripture/packages.lock.json
Labels: testing not required

#3278 Improve contrast of draft history cancelled indicator
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/_draft-history-entry-theme.scss
Labels: testing not required

#3279 Remove UntypedFormControl from share control
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-base.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/project-role-info.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts
Labels: testing not required

#3275 Add index to improve question querying performance
  src/RealtimeServer/scriptureforge/models/question.ts
Labels: testing not required

#3260 SF-3423 Inform user when lacking permission to import chapter
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#3259 Add e2e test for editor and improve other e2e tests
  .github/workflows/e2e-tests.yml
  src/SIL.XForge.Scripture/ClientApp/e2e/e2e-utils.ts
  src/SIL.XForge.Scripture/ClientApp/e2e/e2e.mts
  src/SIL.XForge.Scripture/ClientApp/e2e/record-mobile-checking-videos.mts
  src/SIL.XForge.Scripture/ClientApp/e2e/test-definitions.ts
  src/SIL.XForge.Scripture/ClientApp/e2e/test_characterization.json
  src/SIL.XForge.Scripture/ClientApp/e2e/user-emulator.mts
  src/SIL.XForge.Scripture/ClientApp/e2e/workflows/edit-translation.ts
  src/SIL.XForge.Scripture/ClientApp/e2e/workflows/generate-draft.ts
  src/SIL.XForge.Scripture/ClientApp/e2e/workflows/localized-screenshots.ts
Labels: testing not required

#3285 Add short name to confirm sources component
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts
Labels: testing not required

#3286 Update e2e draft generation to not require being a Serval admin
  src/SIL.XForge.Scripture/ClientApp/e2e/workflows/generate-draft.ts
Labels: testing not required

#3293 Add types to project select form control
  src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
Labels: testing not required
