Repository sillsdev/web-xforge, pull requests merged in 2025-09, with the labels that each got.

#3414 Enable promise linting in RealtimeServer
  src/RealtimeServer/.eslintrc.json
  src/RealtimeServer/scriptureforge/migrator.ts
  src/RealtimeServer/scriptureforge/services/note-thread-service.ts
  src/RealtimeServer/scriptureforge/services/question-service.ts
Labels: testing not required

#3421 Hotfix: Revert "Switch to new DBL server in prod environment (#3385)"
  src/SIL.XForge.Scripture/Services/ParatextService.cs
Labels: fix recent change

#3423 Update actions/checkout and actions/setup-dotnet to version 5
  .github/workflows/build-and-test.yml
  .github/workflows/chromatic.yml
  .github/workflows/ci-lint-prettier.yml
  .github/workflows/ci-production-build.yml
  .github/workflows/codeql.yml
  .github/workflows/compute-next-version.yml
  .github/workflows/docker-dev.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/grit.yml
  .github/workflows/release-live.yml
  .github/workflows/release-qa.yml
  .github/workflows/release.yml
  .github/workflows/update-font-list.yml
  .github/workflows/update-localizations.yml
  .github/workflows/zizmor.yml
Labels: testing not required

#3413 SF-3524 Fix bug where notes in headings cannot be reopened after editing
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing complete

#3392 SF-3505 Add Lynx options in settings and remove feature flag
  src/RealtimeServer/scriptureforge/models/lynx-config.ts
  src/RealtimeServer/scriptureforge/models/sf-project-test-data.ts
  src/RealtimeServer/scriptureforge/models/sf-project.ts
  src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/sf-project-settings.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-editor-objects/lynx-insight-editor-objects.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-editor-objects/lynx-insight-editor-objects.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-editor-objects/lynx-insight-editor-objects.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-workspace-factory.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-workspace.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-workspace.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
  src/SIL.XForge.Scripture/Models/LynxConfig.cs
  src/SIL.XForge.Scripture/Models/SFProject.cs
  src/SIL.XForge.Scripture/Models/SFProjectSettings.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
Labels: testing complete

#3424 Create new browser context for every e2e text run
  src/SIL.XForge.Scripture/ClientApp/e2e/e2e.mts
Labels: testing not required, e2e

#3428 Update lynx lib npm package refs
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
Labels: testing not required

#3430 SF-3555 Improve Lynx settings text
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#3405 Add Grit check to prevent incorrect mock patterns
  .grit/patterns/no_mock_patterns_outside_mocks.md
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
Labels: testing not required

#3416 SF-3543 Rethrow webhook errors caused by Serval communication issues
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
Labels: testing complete

#3445 Be specific about draft ability in app.component.spec
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
Labels: testing not required

#3425 SF-3528 Require users to select formatting options the first time
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/_draft-history-entry-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#3436 SF-3563 Fix offline support for community checking users
  src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.ts
Labels: testing complete

#3437 SF-3557 Improve book progress accuracy for incomplete books
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
Labels: testing complete

#3426 SF-3545 Add per-user lynx toggle to translator settings
  src/RealtimeServer/scriptureforge/models/lynx-insight-user-data.ts
  src/RealtimeServer/scriptureforge/services/sf-project-migrations.spec.ts
  src/RealtimeServer/scriptureforge/services/sf-project-user-config-migrations.spec.ts
  src/RealtimeServer/scriptureforge/services/sf-project-user-config-service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-editor-objects/lynx-insight-editor-objects.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-editor-objects/lynx-insight-editor-objects.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-state.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translator-settings-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translator-settings-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translator-settings-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translator-settings-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/Models/LynxConfig.cs
  src/SIL.XForge.Scripture/Models/LynxInsightUserData.cs
Labels: new feature, testing complete

#3441 SF-2935 Use mat-tooltip consistently
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/multi-viewer/multi-viewer.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts
Labels: testing complete

#3444 Enable no-floating-promises lint rule in ClientApp
  src/SIL.XForge.Scripture/ClientApp/.eslintrc.json
Labels: testing not required

#3390 Store resource usage report in more persistent location
  src/RealtimeServer/common/diagnostics.ts
  src/RealtimeServer/common/resource-monitor.spec.ts
  src/RealtimeServer/common/resource-monitor.ts
Labels: testing not required

#3438 SF-3549 Position notes correctly in introductory paragraphs
  src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
Labels: testing complete

#3456 Update node dependencies
  scripts/db_tools/package-lock.json
  src/RealtimeServer/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
Labels: testing not required, e2e

#3464 Reword "line breaks" to "paragraph breaks"
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-usfm-format/draft-usfm-format.component.html
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#3465 Fix GHA failures caused dpkg finding no .NET packages installed
  .github/workflows/build-and-test.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/release.yml
Labels: critical path

#3447 SF-3566 Guide user to formatting options on draft tab
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#3457 SF-3561 Fix lynx autocomplete error when nav to book with no first chapter
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-workspace.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-workspace.service.ts
Labels: testing complete

#3453 SF-3560 Fix permissions check for lynx to include role
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing complete

#3451 SF-3573 Exclude blank line tags from segment count
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts
Labels: testing complete

#3481 dev: break up test-utils.ts long lines
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-utils.ts
Labels: testing not required

#3484 ci: make the disallowed tokens error more clear
  .github/workflows/build-and-test.yml
Labels: testing not required
