Repository sillsdev/web-xforge, pull requests merged in 2025-05, with the labels that each got.

#3161 Improve theme support for translate editing
  src/SIL.XForge.Scripture/ClientApp/src/_text.scss
  src/SIL.XForge.Scripture/ClientApp/src/_usx.scss
  src/SIL.XForge.Scripture/ClientApp/src/_variables.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/copyright-banner/copyright-banner.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/notice/notice.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/_sf-tab-group-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-header/tab-header.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/_biblical-terms-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/_editor-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/_editor-draft-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/editor-history.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/_note-dialog-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/themes/_default.scss
Labels: testing not required

#3184 SF-3349 Prompt user when leaving draft sources with unsaved changes
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/project-router.guard.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/project-router.guard.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-routing.module.ts
Labels: ready to test

#3190 Use writing system to determine fallback font and add Noto fonts
  .vscode/settings.json
  scripts/update_font_list.mts
  scripts/update_writing_system_font_map.mts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/font.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/font.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/font.stories.ts
  src/SIL.XForge.Scripture/fonts.json
  src/SIL.XForge.Scripture/writing_system_font_map.json
Labels: testing not required

#3189 Add missing indexes to MongoDB
  src/RealtimeServer/common/models/user.ts
  src/RealtimeServer/common/services/doc-service.ts
  src/RealtimeServer/scriptureforge/models/sf-project.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/indexeddb-offline-store.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts
Labels: testing not required

#3187 SF-3333b Reduce calls to the DBL, PT, and RTS when configuring sources
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge/Services/ProjectService.cs
Labels: testing not required

#3194 Update query to find a project's most recent sync failures
  mongodb/Projects/SyncFailureCause.mongodb
Labels: testing not required

#3196 SF-3166b Avoid using cache when generating revision summaries
  src/SIL.XForge.Scripture/Services/ParatextService.cs
Labels: testing not required

#3193 SF-3027 Consistent Page Title Styling
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.scss
Labels: testing not required

#3198 Fix realtime server crash when querying for notes for an invalid project
  src/RealtimeServer/scriptureforge/realtime-server.ts
Labels: bug, critical path, testing not required

#3192 SF-3334 Fix bug with updating scripture audio
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts
Labels: ready to test

#3191 SF-3349b Only prompt user about unsaved source changes
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/project-router.guard.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/project-router.guard.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.stories.ts
Labels: critical path, testing complete

#3202 SF-3337 Fix CC progress donut on page refresh
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/donut-chart/donut-chart.component.ts
Labels: ready to test

#3203 SF-3380 Fix remaining white label display bugs
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/icons/sd.ico
  src/SIL.XForge.Scripture/ClientApp/src/index.html
  src/SIL.XForge.Scripture/Pages/Shared/_Layout.cshtml
Labels: testing complete

#3180 SF-3306 Add initial draft history UI
  scripts/db_tools/parse-version.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/event-metrics/event-metrics-log.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/build-dto.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-download-button/draft-download-button.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-download-button/draft-download-button.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-download-button/draft-download-button.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-download-button/draft-download-button.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/_draft-history-entry-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-list.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-list.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-list.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-list.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
  src/SIL.XForge.Scripture/Controllers/MachineApiController.cs
  src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
  src/SIL.XForge.Scripture/Models/ServalBuildAdditionalInfo.cs
  src/SIL.XForge.Scripture/Services/IMachineApiService.cs
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
Labels: testing complete

#3206 Rework deprecated mat tree classes
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.ts
Labels: testing not required

#3207 SF-3370 Improve lynx processing time when opening large projects
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-state.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-workspace.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-workspace.service.ts
Labels: testing not required

#3211 Fix CountBooksDrafted Mongo query
  mongodb/EventMetrics/CountBooksDrafted.mongodb
Labels: testing not required

#3212 Fix QA site mistakenly linking to wrong help site
  src/SIL.XForge.Scripture/ClientApp/src/environments/environment.staging.ts
Labels: testing not required

#3201 SF-3331 Fix training source checkbox runoff for small screens
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss
Labels: testing complete

#3209 Update CSharpier to 1.0.1
  .config/dotnet-tools.json
  .csharpierignore
  .lintstagedrc.yml
  src/Migrations/PtdaSyncAll.Tests/PtdaSyncRunnerTests.cs
  src/SIL.XForge.Scripture/Services/NotesFormatter.cs
  src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge/DataAccess/MemoryUpdateBuilder.cs
  src/SIL.XForge/DataAccess/WritableContractResolver.cs
  src/SIL.XForge/Realtime/Json0/Json0OpBuilder.cs
  src/SIL.XForge/Realtime/RichText/Delta.cs
  test/SIL.Converters.Usj.Tests/TestData.cs
  test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsRpcControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/JwtTokenHelperTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/PreTranslationServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SharingLogicWrapperTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SyncServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/TrainingDataServiceTests.cs
  test/SIL.XForge.Tests/DataAccess/MongoRepositoryTests.cs
  test/SIL.XForge.Tests/Realtime/ConnectionTests.cs
  test/SIL.XForge.Tests/Services/ProjectServiceTests.cs
  test/SIL.XForge.Tests/Services/UserServiceTests.cs
Labels: testing not required

#3215 Fix button color in diagnostics panel
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.scss
Labels: testing not required

#3216 SF-3388 Fix 524 errors when viewing chapter history
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  tools/CommitGenerator/CommitGenerator.csproj
  tools/CommitGenerator/CommitGenerator.sln
  tools/CommitGenerator/Program.cs
Labels: testing not required

#3217 SF-3384 Refresh Roles and Permissions form when network connection changes
  src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.spec.ts
Labels: ready to test

#3222 Update workflows to support merge queues
  .github/workflows/build-and-test.yml
  .github/workflows/chromatic.yml
  .github/workflows/ci-lint-prettier.yml
  .github/workflows/ci-production-build.yml
  .github/workflows/codeql.yml
  .github/workflows/grit.yml
  .github/workflows/zizmor.yml
Labels: testing not required

#3225 SF-3127b Fix line on home screen by rebuilding SCSS
  src/SIL.XForge.Scripture/wwwroot/css/sf.min.css
Labels: testing not required

#3226 dev: add updated live sass compiler recommendation
  .vscode/extensions.json
Labels: testing not required
