Repository sillsdev/web-xforge, pull requests merged in 2025-07, with the labels that each got.

#3291 Update count books drafted query to support new event metrics format
  mongodb/EventMetrics/CountBooksDrafted.mongodb
Labels: testing not required

#3288 SF-3430 Fix insight loading on editor edit
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-state.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-state.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-workspace.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-workspace.service.ts
Labels: ready to test

#3294 Fix usfmConfig in the sf_project validation schema
  src/RealtimeServer/scriptureforge/services/sf-project-service.ts
Labels: testing not required

#3290 SF-3444 Prevent error when rapidly clicking Lynx panel insights
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-overlay.service.ts
Labels: ready to test

#3261 SF-3276 Highlight text in project select when user clicks the input
  src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts
Labels: ready to test

#3301 Update test characterization script to eventually terminate
  src/SIL.XForge.Scripture/ClientApp/e2e/characterize-tests.mts
Labels: testing not required

#3299 Fix e2e test characterization saving Playwright trace
  src/SIL.XForge.Scripture/ClientApp/e2e/characterize-tests.mts
Labels: testing not required

#3277 SF-3422 Allow source projects with observer permission to sync
  src/SIL.XForge.Scripture/Models/SyncMetrics.cs
  src/SIL.XForge.Scripture/Services/IParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  src/SIL.XForge.Scripture/Services/SharingLogicWrapper.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SharingLogicWrapperTests.cs
Labels: testing complete

#3304 Include feature flags in error report metadata
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/exception-handling.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
Labels: testing not required

#3308 SF-3462 Add timezone to event log timestamp
  src/SIL.XForge.Scripture/ClientApp/src/app/event-metrics/event-metrics-log.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/owner/owner.component.html
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/owner/owner.component.ts
Labels: testing not required

#3309 Add dark theme support to permissions viewer
  src/SIL.XForge.Scripture/ClientApp/src/app/permissions-viewer/_permissions-viewer-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/permissions-viewer/permissions-viewer.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
Labels: testing not required

#3303 SF-3043 Update tab header localizations when locale updated
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/base-services/tab-factory.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-request.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-request.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-factory.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-factory.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.ts
Labels: ready to test

#3312 SF-3470 Use the rights by role permissions for the machine API backend
  src/RealtimeServer/scriptureforge/rightsByRole.json
  src/RealtimeServer/scriptureforge/services/training-data-service.spec.ts
  src/SIL.XForge.Scripture/Models/MachineApi.cs
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  src/SIL.XForge.Scripture/Services/TrainingDataService.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/TrainingDataServiceTests.cs
Labels: testing complete

#3297 SF-3454 Fix remaining issues with the new draft user interface
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
Labels: ready to test

#3316 Add tags to Serval jobs based on the Scripture Forge environment
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
Labels: testing not required

#3321 Update e2e screenshot sizes to fit new draft sources page
  src/SIL.XForge.Scripture/ClientApp/e2e/workflows/localized-screenshots.ts
Labels: testing not required

#3320 SF-3397 Synchronize drafting sources if needed when configured
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.html
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: testing not required

#3263 Remove unnecessary horizontal scroll in RTL UI
  src/SIL.XForge.Scripture/ClientApp/src/styles.scss
Labels: testing not required

#3311 SF-3419 Remove Lynx problems panel quotes and improve styling
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-util.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/util/string-util.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/util/string-util.ts
Labels: testing complete

#3325 Localize training files label in draft generation stepper
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#3327 Add community checking screenshots to e2e tests
  src/SIL.XForge.Scripture/ClientApp/e2e/workflows/localized-screenshots.ts
Labels: testing not required

#3326 SF-3435 Save fast training and echo settings across draft builds
  src/RealtimeServer/scriptureforge/models/translate-config.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
  src/SIL.XForge.Scripture/Models/DraftConfig.cs
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
Labels: ready to test

#3324 SF-1007 Allow selecting questions with keyboard
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.scss
Labels: ready to test

#3331 metrics: Do not jsonSizeOf(undefined)
  src/RealtimeServer/common/resource-monitor.ts
Labels: testing not required
