Repository sillsdev/web-xforge, pull requests merged in 2025-08, with the labels that each got.

#3329 Update project query count to be able to exclude test projects
  mongodb/Projects/ProjectsOverTime.mongodb
Labels: testing not required

#3334 SF-3370 Add web worker and improve blot formats delta creation
  .vscode/settings.json
  src/SIL.XForge.Scripture/ClientApp/angular.json
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/quill-services/insight-formatting-utils.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/quill-services/insight-formatting-utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/quill-services/insight-formatting.worker.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/quill-services/quill-insight-render.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/tsconfig.spec.json
  src/SIL.XForge.Scripture/ClientApp/tsconfig.worker.json
  src/SIL.XForge.Scripture/Startup.cs
Labels: testing complete

#2013 SF-2193 Add bubble splash effect that can be added to various buttons
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.directive.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.stories.ts
Labels: new feature

#3351 Attempt to fix Storybook avatar tests
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/avatar/avatar.stories.ts
Labels: testing not required

#3352 Update capitalization of pt-BR help URL to match Docusaurus
  src/SIL.XForge.Scripture/locales.json
Labels: testing not required

#3346 SF-2904 Store Paratext project visibility in the project document
  src/RealtimeServer/scriptureforge/models/sf-project.ts
  src/RealtimeServer/scriptureforge/services/sf-project-service.ts
  src/SIL.XForge.Scripture/Models/ParatextSettings.cs
  src/SIL.XForge.Scripture/Models/SFProject.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs
Labels: testing not required

#3337 Copilot instructions: running frontend tests
  .github/copilot-instructions.md
Labels: testing not required

#3353 Improve draft history configuration heading
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#3355 SF-3443 SF-3494 Filter out Lynx insights for chapters that cannot be edited
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-filter.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-filter.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-state.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-state.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insights-panel/lynx-insights-panel.component.ts
Labels: testing complete

#3358 Add project short name to unconnected projects on draft page
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
Labels: testing not required

#3356 SF-3492 Show what source a draft was translated from
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.ts
Labels: testing complete

#3343 SF-3479 Show previous completed drafts when opening draft tab
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
Labels: testing complete

#3365 Update dotnet dependencies
  src/Help/UpdateHelp/UpdateHelp.csproj
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/packages.lock.json
  src/SIL.XForge/SIL.XForge.csproj
  src/SIL.XForge/packages.lock.json
  test/SIL.Converters.Usj.Tests/SIL.Converters.Usj.Tests.csproj
  test/SIL.Converters.Usj.Tests/UsxToUsjTests.cs
  test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
  test/SIL.XForge.Tests/DataAccess/BsonValueConverterTests.cs
  test/SIL.XForge.Tests/SIL.XForge.Tests.csproj
  tools/CommentGenerator/CommentGenerator.csproj
  tools/CommitGenerator/CommitGenerator.csproj
  tools/RepoInfo/RepoInfo.csproj
  tools/ServalBuildReport/ServalBuildReport.csproj
Labels: testing not required

#3368 Add component to list Serval draft jobs
  src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/draft-jobs.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/draft-jobs.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/draft-jobs.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/job-events-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/job-events-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/job-events-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/site-event-metrics.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/site-event-metrics.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/site-event-metrics.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/system-administration.component.scss
  src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
  src/SIL.XForge.Scripture/Services/ISFProjectService.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs
  src/SIL.XForge/Services/EventMetricService.cs
  src/SIL.XForge/Services/IEventMetricService.cs
  test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsRpcControllerTests.cs
  test/SIL.XForge.Tests/Services/EventMetricServiceTests.cs
Labels: testing not required

#3369 Adjust color of text on checking overview page
  src/SIL.XForge.Scripture/ClientApp/src/_variables.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss
Labels: testing not required

#3371 Update localized screenshots workflow to be more robust
  src/SIL.XForge.Scripture/ClientApp/e2e/workflows/localized-screenshots.ts
Labels: testing not required

#3380 Update e2e tests to work with Angular 19
  src/SIL.XForge.Scripture/ClientApp/e2e/e2e-utils.ts
  src/SIL.XForge.Scripture/ClientApp/e2e/workflows/community-checking.ts
  src/SIL.XForge.Scripture/ClientApp/e2e/workflows/edit-translation.ts
Labels: testing not required

#3367 SF-3451 Fix Lynx overlay RTL styles
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-overlay.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-overlay.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-overlay/lynx-insight-overlay.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-overlay/lynx-insight-overlay.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-overlay/lynx-insight-overlay.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-overlay/lynx-insight-overlay.component.ts
Labels: testing complete

#3374 SF-3497 Fix no Lynx overlay when Lynx problems panel nav to another chapter
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/base-services/insight-render.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-editor-objects/lynx-insight-editor-objects.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-editor-objects/lynx-insight-editor-objects.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/lynx-insight-overlay/lynx-insight-overlay.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/lynx/insights/quill-services/quill-insight-render.service.ts
Labels: testing complete

#3387 Increase interaction speed of default e2e preset
  src/SIL.XForge.Scripture/ClientApp/e2e/presets.ts
Labels: testing not required

#3386 Fix word wrap of status text in draft history
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pseudo-localization.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pseudo-localization.ts
Labels: testing not required

#3385 Switch to new DBL server in prod environment
  src/SIL.XForge.Scripture/Services/ParatextService.cs
Labels: testing not required

#3357 SF-3476 Add error reporting when applying draft fails
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-progress-dialog/draft-apply-progress-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-progress-dialog/draft-apply-progress-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-progress-dialog/draft-apply-progress-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-progress-dialog/draft-apply-progress-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#3378 SF-3512 Do not allow unpaired parentheses in BT renderings
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfvalidators.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sfvalidators.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-term-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-term-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-term-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#3384 SF-3518 Exclude id segment from segment counts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts
Labels: testing complete

#3394 SF-3526 Fix up Serval draft jobs component
  src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/draft-jobs.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/draft-jobs.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/draft-jobs.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.component.ts
Labels: testing not required

#3401 Update wording on draft format options page
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-history-list/draft-history-entry/draft-history-entry.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-usfm-format/_draft-usfm-format-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-usfm-format/draft-usfm-format.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-usfm-format/draft-usfm-format.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#3403 SF-3530 Ignore file not found errors when zipping a Paratext directory
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
Labels: testing not required

#3381 SF-3488 Force refresh when draft config changes remotely
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
Labels: testing complete

#3408 Re-enable portion of e2e tests that were mistakenly disabled
  src/SIL.XForge.Scripture/ClientApp/e2e/workflows/localized-screenshots.ts
Labels: testing not required, e2e

#3404 SF-3531 Allow CSV files containing unmatching quotes
  src/SIL.XForge.Scripture/Services/TrainingDataService.cs
  test/SIL.XForge.Scripture.Tests/Services/TrainingDataServiceTests.cs
Labels: testing complete

#3411 Fix screenshot name in localized_screenshots e2e test
  src/SIL.XForge.Scripture/ClientApp/e2e/workflows/localized-screenshots.ts
Labels: testing not required

#3410 Use production help URL in development environment
  src/SIL.XForge.Scripture/ClientApp/src/environments/environment.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.spec.ts
Labels: testing not required
