Repository sillsdev/web-xforge, pull requests merged in 2025-02, with the labels that each got.

#2989 SF-3171 Add icons to draft generation steps buttons
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
Labels: testing not required

#2983 Add script to check if all external links are valid
  scripts/check_external_urls.mts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url-class.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/external-url.service.ts
Labels: testing not required

#2990 SF-3187 Store the correct language code when migrating resources
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: testing complete

#2984 SF-3176 Add Upload Audio to Questions
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/attach-audio/attach-audio.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/attach-audio/attach-audio.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/attach-audio/attach-audio.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/attach-audio/attach-audio.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
Labels: ready to test

#2991 SF-3185 Add replaceDoc support to realtime server
  src/RealtimeServer/common/index.ts
  src/RealtimeServer/package-lock.json
  src/RealtimeServer/package.json
  src/RealtimeServer/typings/json0-ot-diff.d.ts
  src/SIL.XForge/Models/QueuedAction.cs
  src/SIL.XForge/Realtime/Connection.cs
  src/SIL.XForge/Realtime/Document.cs
  src/SIL.XForge/Realtime/IConnection.cs
  src/SIL.XForge/Realtime/IDocument.cs
  src/SIL.XForge/Realtime/IRealtimeServer.cs
  src/SIL.XForge/Realtime/MemoryConnection.cs
  src/SIL.XForge/Realtime/MemoryDocument.cs
  src/SIL.XForge/Realtime/RealtimeServer.cs
  test/SIL.XForge.Tests/Realtime/ConnectionTests.cs
  test/SIL.XForge.Tests/Realtime/DocumentTests.cs
  test/SIL.XForge.Tests/Realtime/RealtimeServerTests.cs
Labels: testing not required

#2995 SF-3196 Remove Manual link from Help Menu
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
Labels: testing not required

#2994 SF-3193 Fix additional training data option not visible
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
Labels: critical path, ready to test

#2997 Update vscode settings for C# extension changes v2.63.x
  .vscode/settings.json
Labels: testing not required

#3000 Add Busra font
  src/SIL.XForge.Scripture/fonts.json
Labels: testing not required

#3003 SF-3203 Add an API endpoint to join an existing project
  src/SIL.XForge.Scripture/Controllers/ParatextController.cs
  src/SIL.XForge/Services/IProjectService.cs
  src/SIL.XForge/Services/ProjectService.cs
  test/SIL.XForge.Scripture.Tests/Controllers/ParatextControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: testing not required

#3004 Remove dead code from AppComponent
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
Labels: testing not required

#2999 SF-3201 Fix broken editor jump links
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
Labels: bug, will require testing

#3008 Prevent front-end tests from passing when warnings are printed
  .github/workflows/build-and-test.yml
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/attach-audio/attach-audio.component.spec.ts
Labels: testing not required

#3019 Fix common audio test failure
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts
Labels: testing not required

#3010 Add Mongo query to find latest sync results for group of projects
  mongodb/Projects/LatestSyncInfo.mongodb
  mongodb/Projects/SyncFailureCause.mongodb
Labels: testing not required

#3013 SF-3208 Fix resource not showing when user has permission
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: testing not required

#3022 Update definition of corrupted chapter to include insert.link bug
  mongodb/Texts/CorruptedTexts.mongodb
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
Labels: testing not required

#2255 Force Chromatic Rebuild for Storybook
  .github/workflows/chromatic.yml
Labels: testing not required

#2993 SF-2864 Fix icon run-off on smaller mobile devices
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.scss
Labels: testing complete

#3002 SF-3202 Add IsDraftingEnabled flag to Projects API
  src/SIL.XForge.Scripture/Models/ParatextProject.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: testing not required

#3024 dev: add to manipulate-sharedb tool
  scripts/db_tools/manipulate-sharedb.ts
Labels: testing not required

#3026 Fix naming of ImportQuestionsDialogComponent files
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-confirmation-dialog/import-questions-confirmation-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-confirmation-dialog/import-questions-confirmation-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-confirmation-dialog/import-questions-confirmation-dialog.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
Labels: testing not required

#2998 SF-3138 Update projects list dynamically in Add Resource dialog
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.service.ts
Labels: ready to test

#3021 SF-3206 Display Cancel Draft dialog regardless of build state
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
Labels: ready to test

#3025 Fix tests with verify that do not actually verify
  .github/workflows/build-and-test.yml
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts
Labels: testing not required

#3027 Add checks with Grit
  .github/workflows/grit.yml
  .grit/.gitignore
  .grit/grit.yaml
  .grit/patterns/README.txt
  .grit/patterns/bare_verify.md
  .grit/patterns/bare_when.md
  .grit/patterns/import_from_lodash_es.md
  .grit/patterns/no_internal_imports.md
  .grit/patterns/no_skipped_tests.md
  .grit/patterns/xforge_common_absolute_only.md
  .lgtm/javascript-queries/import-relative-to-project-root.ql
Labels: testing not required

#3031 Update font list
  src/SIL.XForge.Scripture/fonts.json
Labels: testing not required

#3029 Add error message to error report email
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
Labels: testing not required

#3036 Fix dependabot alerts
  .gitignore
  src/RealtimeServer/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/Services/MachineServiceCollectionExtensions.cs
  tools/ServalBuildReport/Program.cs
  tools/ServalBuildReport/ServalBuildReport.csproj
  tools/ServalDownloader/Program.cs
  tools/ServalDownloader/ServalDownloader.csproj
Labels: testing not required

#3028 SF-3217 Cache build dependencies
  .github/workflows/build-and-test.yml
  .github/workflows/chromatic.yml
  .github/workflows/ci-lint-prettier.yml
  .github/workflows/ci-production-build.yml
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  src/SIL.Converters.Usj/SIL.Converters.Usj.csproj
  src/SIL.Converters.Usj/packages.lock.json
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/packages.lock.json
  src/SIL.XForge/SIL.XForge.csproj
  src/SIL.XForge/packages.lock.json
Labels: testing not required

#3041 SF-3220 Fix CodeQL crashes
  .github/workflows/codeql.yml
Labels: testing not required

#3038 SF-3227 Investigate and fix zizmor alerts
  .github/workflows/build-and-test.yml
  .github/workflows/chromatic.yml
  .github/workflows/ci-lint-prettier.yml
  .github/workflows/ci-production-build.yml
  .github/workflows/codeql.yml
  .github/workflows/compute-next-version.yml
  .github/workflows/docker-dev.yml
  .github/workflows/grit.yml
  .github/workflows/release-live.yml
  .github/workflows/release-qa.yml
  .github/workflows/release.yml
  .github/workflows/update-localizations.yml
  .github/workflows/zizmor.yml
Labels: testing not required

#3030 SF-3222 Fix training data files not updated after file uploaded
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/training-data/training-data-multi-select.component.html
Labels: ready to test

#3044 SF-3229 Remove bulk book selection from "Drafting" step
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
Labels: testing not required

#3033 SF-2799 Notify user when previous version is restored
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: ready to test

#3032 Refactor quill-scripture.ts to allow testing
  .vscode/settings.json
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-clipboard.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-clipboard.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-formats/quill-attributors.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-formats/quill-attributors.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-formats/quill-blot-value-types.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-formats/quill-blots.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-formats/quill-blots.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-history.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-history.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-registrations.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-registrations.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-util.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-util.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: testing not required

#3045 ci: rely on called workflow environment secrets
  .github/workflows/release-live.yml
  .github/workflows/release-qa.yml
Labels: testing not required

#3046 Fix workflow cache file path
  .github/workflows/release.yml
Labels: testing not required

#3042 SF-3230 Get draft configuration for language code confirmation from parent
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.stories.ts
Labels: ready to test

#3049 ci: fix release workflow permission
  .github/workflows/release-live.yml
  .github/workflows/release-qa.yml
  .github/workflows/release.yml
Labels: testing not required

#3039 SF-3228 Replace multiple newlines and tabs with space on editor paste
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-clipboard.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-clipboard.ts
Labels: bug, ready to test

#3047 Fix editor NG0955 warning
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab/tab.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-factory.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-factory.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts
Labels: bug, testing not required

#2962 SF-3237 Add page to configure draft sources
  .vscode/settings.json
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-routing.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/activated-project.service.ts
  src/SIL.XForge.Scripture/Controllers/ParatextController.cs
  test/SIL.XForge.Scripture.Tests/Controllers/ParatextControllerTests.cs
Labels: will require testing

#3012 SF-2829 Allow paratext roles that have changed to be updated
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/paratext-project.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/project.service.ts
  src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
  src/SIL.XForge.Scripture/Models/ParatextProject.cs
  src/SIL.XForge.Scripture/Services/ISFProjectService.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: ready to test
