Repository sillsdev/web-xforge, pull requests merged in 2025-03, with the labels that each got.

#3053 Highlight generate draft nav item when editing draft sources
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-routing.module.ts
Labels: testing not required

#3054 Clean up Angular deprecation warnings and lodash imports
  .config/dotnet-tools.json
  src/Migrations/PtdaSyncAll/Program.cs
  src/Migrations/SyncCancel/Program.cs
  src/Migrations/SyncUserToPTUser/Program.cs
  src/Migrations/UsxFormat/Program.cs
  src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-term-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/donut-chart/donut-chart.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n-story.module.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/indexeddb-offline-store.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/memory-realtime-remote-store.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/sharedb-realtime-remote-store.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-projects.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/system-administration/sa-users.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-realtime.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts
  src/SIL.XForge.Scripture/Pages/_ViewStart.cshtml
Labels: testing not required

#3056 Improve wording of role refresh
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.html
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
Labels: testing not required

#3058 Add stories for project select
  src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.stories.ts
Labels: testing not required

#3055 Improve wording of language codes confirmation
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#3059 Internationalize draft sources component
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#3035 SF-3188 Upgrade to ShareDB 5.1.1 on server side
  src/RealtimeServer/common/realtime-server.ts
  src/RealtimeServer/package-lock.json
  src/RealtimeServer/package.json
  src/RealtimeServer/typings/sharedb/index.d.ts
Labels: testing complete

#3050 SF-3215 Hide Auto Draft tab if the user doesn't have permission
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.ts
Labels: testing complete

#3051 SF-3211 Show source panel in editor if project has source selected
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-text/checking-text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/text-chooser-dialog/text-chooser-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/translate-metrics-session.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
Labels: testing complete

#3062 SF-3240 Fix crashes when a draft book has an invalid book id
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: ready to test

#3060 SF-3213 Allow users to create chapters when adding a draft to a book
  src/RealtimeServer/scriptureforge/rightsByRole.json
  src/RealtimeServer/scriptureforge/services/text-service.spec.ts
  src/RealtimeServer/scriptureforge/services/text-service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/text-doc.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/text-doc.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts
  src/SIL.XForge.Scripture/Controllers/SFProjectsRpcController.cs
  src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
  src/SIL.XForge.Scripture/Services/ISFProjectService.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsRpcControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: ready to test

#3052 SF-3212 Create 'unknown' blot as fallback blot
  src/SIL.XForge.Scripture/ClientApp/src/_text.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-formats/quill-blots.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-formats/quill-blots.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-registrations.ts
Labels: ready to test

#3065 SF-3242 Show option to add draft to a different project to translators
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.ts
Labels: ready to test

#3067 Fix selector in editor component test
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
Labels: testing not required

#3071 Fix permissions of update-localizations.yml
  .github/workflows/update-localizations.yml
Labels: testing not required

#3068 Add support for arbitrary number of sources in Serval admin components
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.ts
Labels: testing not required

#3043 SF-3205 Handle start draft requests when a job is already running
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#3076 SF-3226 Clarify wording for canceling draft
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#3070 Add query to count users by first role over time
  mongodb/Users/CountFirstRolesOverTime.mongodb
Labels: testing not required

#3077 Remove a number of unneeded non-null assertions
  .grit/patterns/remove_non_null_assertion.md
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-input-form/checking-input-form.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-history.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/mock-pretranslation-machine-api.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/editor-history.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/indexeddb-offline-store.ts
Labels: testing not required

#3081 SF-3249 Fix error when commenter and viewers navigate to project texts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.ts
Labels: critical path, testing complete

#3073 SF-3248 Refactor DraftSourcesService to support an arbitrary number of sources
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts
Labels: testing complete

#3086 Update validation schema to support ShareDB 5.1.1
  src/RealtimeServer/common/services/doc-service.ts
Labels: testing not required

#3089 Fix language code confirmation in draft sources component
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.ts
Labels: testing not required

#3093 Fix appearance of draft generation error button
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
Labels: testing not required

#3069 SF-3238 Transition to Draft sources component
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
Labels: ready to test

#3094 Improve draft sources accordion UI
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#3098 SF-3260 Show error when draft fails because source is not specified
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
Labels: testing not required

#3082 SF-3218 Update audio cache for questions when needed
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts
Labels: will require testing, ready to test

#3064 SF-3188b Upgrade to sharedb 5.1.1 on client app
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
Labels: ready to test

#3103 Fix project select track expression
  src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.html
Labels: testing not required

#3100 SF-3214 Allow project to start a draft when alternate training or drafting source is set
  src/SIL.XForge.Scripture/Services/IMachineProjectService.cs
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: critical path, testing complete

#3101 SF-3273 Require all source-side languages to be the same
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts
Labels: critical path, testing complete

#3102 SF-3267 Show notice to translator when draft sources not set
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: critical path, ready to test

#3085 SF-3245 Fix quill editor scroll and hidden app notice
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
Labels: ready to test

#3107 SF-3280 Fix login redirect loop
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
Labels: testing not required

#3106 Remove unused locale code logic from draft utils
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts
Labels: testing not required

#3111 Add Mongo query to count draft jobs by date
  mongodb/EventMetrics/CountDraftJobsByDate.mongodb
Labels: testing not required

#3109 Add language code normalization logic to draft sources component
  scripts/update_language_code_map.mts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.stories.ts
  src/SIL.XForge.Scripture/language_code_mapping.json
Labels: testing not required

#3112 Use nullish coalescing assignment when possible
  .grit/patterns/import_from_lodash_es.md
  .grit/patterns/missed_nullish_assignment_opportunity.md
  .grit/patterns/xforge_common_absolute_only.md
  scripts/update_font_list.mts
  src/RealtimeServer/common/metadata-db.ts
  src/RealtimeServer/common/realtime-server.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/text-doc.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/machine-api/remote-translation-engine.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-state/tab-state.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-editor-registration/quill-history.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/segment.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/indexeddb-offline-store.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/models/realtime-doc.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/test-realtime.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
Labels: testing not required

#3108 SF-3285 Remove SMS login logic from app
  src/RealtimeServer/common/models/user.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
  src/SIL.XForge/Services/AuthService.cs
  src/SIL.XForge/Services/IAuthService.cs
  src/SIL.XForge/Services/UserService.cs
  test/SIL.XForge.Tests/Services/UserServiceTests.cs
Labels: testing not required

#3110 Add query to count distinct books drafted
  mongodb/EventMetrics/CountBooksDrafted.mongodb
Labels: testing not required

#3104 SF-3274 Update the translation engine instead of recreating on language change
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/Services/IMachineApiService.cs
  src/SIL.XForge.Scripture/Services/ISFProjectService.cs
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  src/SIL.XForge.Scripture/Services/PreTranslationService.cs
  src/SIL.XForge.Scripture/packages.lock.json
  test/SIL.XForge.Scripture.Tests/Controllers/MachineApiControllerTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/PreTranslationServiceTests.cs
  tools/ServalBuildReport/ServalBuildReport.csproj
  tools/ServalDownloader/ServalDownloader.csproj
Labels: testing not required

#3118 Update supported versions list
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/utils.ts
Labels: testing not required

#3116 SF-3286 Fix sync failed when chapters missing
  src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
  test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
Labels: critical path, ready to test

#3088 SF-3259 Fix resources not showing copyright notices
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/copyright-banner/copyright-banner.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/copyright-banner/copyright-banner.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/copyright-banner/copyright-banner.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/copyright-banner/copyright-banner.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-resource/editor-resource.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-resource/editor-resource.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-resource/editor-resource.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate.module.ts
Labels: ready to test

#3115 Add a USJ and Delta roundtrip tool
  src/SIL.Converters.Usj/UsxToUsj.cs
  test/SIL.Converters.Usj.Tests/TestData.cs
  test/SIL.Converters.Usj.Tests/UsxToUsjTests.cs
  tools/Roundtrip/ConsoleExceptionHandler.cs
  tools/Roundtrip/Program.cs
  tools/Roundtrip/Roundtrip.csproj
  tools/Roundtrip/Roundtrip.sln
  tools/Roundtrip/RoundtripMethod.cs
  tools/Roundtrip/SequentialGuidService.cs
  tools/Roundtrip/usfm.sty
  tools/Roundtrip/usx-sf.xsd
Labels: testing not required

#3121 Remove auto draft terminology for consistency
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#3119 SF-3232 Allow chapter numbers to have footnotes
  src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
  test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
Labels: testing complete

#3128 SF-3269 Show a warning dialog when draft request is already queued
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
Labels: testing not required

#2967 SF-3159 Upgrade to SharpZipLib
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
  src/SIL.XForge.Scripture/packages.lock.json
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: will require testing

#3126 SF-3288 Handle draft source projects that lack language codes
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/paratext-project.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/language-codes-confirmation/language-codes-confirmation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#3123 SF-3195 Allow resources from DBL to be downloaded by Serval Admins
  src/SIL.XForge.Scripture/Controllers/ParatextController.cs
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
Labels: testing not required

#3130 Update node dependencies
  scripts/db_tools/package-lock.json
  src/RealtimeServer/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
Labels: testing not required

#3129 Update dotnet dependencies
  src/Help/UpdateHelp/UpdateHelp.csproj
  src/Migrations/BackoutCommits/BackoutCommits.csproj
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/packages.lock.json
  src/SIL.XForge/SIL.XForge.csproj
  src/SIL.XForge/Services/AuthServiceCollectionExtensions.cs
  src/SIL.XForge/Services/UserAccessor.cs
  src/SIL.XForge/packages.lock.json
  test/SIL.Converters.Usj.Tests/SIL.Converters.Usj.Tests.csproj
  test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
  test/SIL.XForge.Tests/DataAccess/BsonValueConverterTests.cs
  test/SIL.XForge.Tests/SIL.XForge.Tests.csproj
  test/SIL.XForge.Tests/Services/TokenHelper.cs
  test/SIL.XForge.Tests/Services/UserAccessorTests.cs
  tools/RepoInfo/Program.cs
  tools/ServalBuildReport/ServalBuildReport.csproj
Labels: testing not required

#3134 SF-3300 Retrieve the build id from the cancel build action on Serval
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  src/SIL.XForge.Scripture/packages.lock.json
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
  tools/ServalBuildReport/ServalBuildReport.csproj
  tools/ServalDownloader/ServalDownloader.csproj
Labels: testing not required
