Repository sillsdev/web-xforge, pull requests merged in 2025-04, with the labels that each got.

#3099 SF-3219 Add a message to drafting advertising the Serval USFM changes
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing not required

#3136 Fix project reference without a matching metadata reference warning
  src/SIL.Converters.Usj/SIL.Converters.Usj.csproj
Labels: testing not required

#3138 SF-3294 Fix text overflow on share project role select
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts
Labels: testing not required

#3122 SF-3204 Do not show project deleted for Serval Admin viewing Event Log
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
Labels: testing complete

#3133 SF-3268 Fix clearing first training source
  src/SIL.XForge.Scripture/ClientApp/src/app/core/models/paratext-project.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project-select/project-select.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/type-utils.ts
  src/SIL.XForge.Scripture/ClientApp/src/utils.spec.ts
Labels: testing complete

#3124 SF-3189 Fix project deleted dialog appearing more than necessary
  src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
Labels: ready to test

#3131 SF-3297 Allow importing questions from Excel files
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/csv-service.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/csv-service.service.ts
  src/SIL.XForge.Scripture/Controllers/SFProjectsUploadController.cs
  src/SIL.XForge.Scripture/Services/ITrainingDataService.cs
  src/SIL.XForge.Scripture/Services/TrainingDataService.cs
  test/SIL.XForge.Scripture.Tests/Controllers/SFProjectsUploadControllerTests.cs
Labels: ready to test

#3105 SF-3253 Navigate to last location, if possible
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/resume-base.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/resume-checking.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/resume-checking.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/resume-translate.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/resume-translate.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts
Labels: ready to test

#3144 Add url links for Indonesian on Help Site
  src/SIL.XForge.Scripture/locales.json
Labels: testing not required

#3142 Show chapter number when archiving questions in chapter
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
Labels: testing not required

#3140 SF-3304 Do not sync each project more than once on build
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineApiServiceTests.cs
Labels: testing not required

#3143 Add workflow to update list of supported fonts
  .github/workflows/update-font-list.yml
Labels: testing not required

#3125 SF-3216 Warn user when no training books are available
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: ready to test

#3074 SF-2984 Implement Material Theme
  scripts/db_tools/parse-version.ts
  src/SIL.XForge.Scripture/ClientApp/.storybook/preview.ts
  src/SIL.XForge.Scripture/ClientApp/angular.json
  src/SIL.XForge.Scripture/ClientApp/src/_variables.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/_app-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/_checking-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/_checking-questions-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/_my-projects-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/_navigation-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/_sf-tab-group-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-header/tab-header.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/biblical-terms/biblical-terms.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/_draft-generation-steps-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-history/history-chooser/history-chooser.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/index.html
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/styles.scss
  src/SIL.XForge.Scripture/ClientApp/src/themes/_default.scss
  src/SIL.XForge.Scripture/ClientApp/src/themes/themes.scss
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/theme.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/theme.service.ts
Labels: ready to test

#3154 Improve theme support for drafting
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/_book-multi-select-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/_confirm-sources-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/confirm-sources/confirm-sources.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/_draft-sources-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
Labels: testing not required

#3148 SF-3271 Prevent Save & Sync of draft sources when offline
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#3157 Add DBL resource support to the roundtrip tool
  src/SIL.XForge.Scripture/Services/DeltaUsxMapper.cs
  src/SIL.XForge.Scripture/Services/ParatextZippedResourcePasswordProvider.cs
  src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
  test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextZippedResourcePasswordProviderTests.cs
  tools/Roundtrip/Program.cs
  tools/Roundtrip/README.md
  tools/Roundtrip/Roundtrip.csproj
Labels: testing not required

#3152 Remove permanently enabled feature flags
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/project-router.guard.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.stories.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
Labels: testing not required

#3150 Change Path.Combine to Path.Join to fix CodeQL warnings
  src/Help/UpdateHelp/Program.cs
  src/Migrations/BackoutCommits/SyncAllService.cs
  src/Migrations/PTDDCloneAll.Tests/CloneAllServiceTests.cs
  src/Migrations/PTDDCloneAll/CloneAllService.cs
  src/Migrations/PtdaSyncAll.Tests/PtdaSyncRunnerTests.cs
  src/Migrations/PtdaSyncAll/PtdaSyncRunner.cs
  src/Migrations/SourceTargetSplitting/Program.cs
  src/Migrations/SourceTargetSplitting/SourceScrTextCollection.cs
  src/Migrations/UsxFormat/Program.cs
  src/SIL.XForge.Scripture/Controllers/SFProjectsUploadController.cs
  src/SIL.XForge.Scripture/Migrator.cs
  src/SIL.XForge.Scripture/Services/ApiDocumentationExtensions.cs
  src/SIL.XForge.Scripture/Services/LazyScrTextCollection.cs
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
  src/SIL.XForge.Scripture/Services/SFProjectRights.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge.Scripture/Services/SFScrTextCollection.cs
  src/SIL.XForge.Scripture/Services/TrainingDataService.cs
  src/SIL.XForge.Scripture/Services/TransceleratorService.cs
  src/SIL.XForge.Scripture/Startup.cs
  src/SIL.XForge/Realtime/RealtimeServer.cs
  src/SIL.XForge/Services/ProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs
  test/SIL.XForge.Scripture.Tests/Services/LazyScrTextCollectionTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/MockCommentTags.cs
  test/SIL.XForge.Scripture.Tests/Services/NotesFormatterTests.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
  test/SIL.XForge.Scripture.Tests/Services/TrainingDataServiceTests.cs
  test/SIL.XForge.Tests/Services/ProjectServiceTests.cs
  tools/RepoInfo/Program.cs
  tools/Roundtrip/Program.cs
  tools/ServalBuildReport/Program.cs
  tools/ServalDownloader/Program.cs
Labels: testing not required

#3153 Improve theme support for community checking
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/_checking-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/_checking-answers-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/_checking-comments-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/_checking-questions-theme.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions/checking-questions.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss
Labels: testing not required

#3163 SF-3314 Fix installation of new DBL resources (#3149)
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/SFInstallableDblResource.cs
  src/SIL.XForge/Services/FileSystemService.cs
  src/SIL.XForge/Services/IFileSystemService.cs
  test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
Labels: critical path

#3165 Add MongoDB query to find references to missing users
  mongodb/Projects/FindReferencesToMissingUsers.mongodb
Labels: testing not required

#3162 Combine the fast training and echo feature flags into developer tools
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts
  src/SIL.XForge.Scripture/appsettings.json
Labels: testing not required

#3160 Update ParatextData to 9.5.0.12
  src/Migrations/BackoutCommits/BackoutCommits.csproj
  src/SIL.XForge.Scripture/ClientApp/src/assets/icons/TagIcons/spelling2.png
  src/SIL.XForge.Scripture/SIL.XForge.Scripture.csproj
  src/SIL.XForge.Scripture/packages.lock.json
  tools/CommentGenerator/CommentGenerator.csproj
  tools/RepoInfo/RepoInfo.csproj
  tools/Roundtrip/Roundtrip.csproj
Labels: testing not required

#3166 Update build-angular to fix vite dependabot alerts
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
Labels: testing not required

#3164 SF-3326 Fix spacing of invite form on mobile
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/share/share-control.component.scss
Labels: testing complete

#3075 SF-3209 Enable "manage audio" for users without questions permission
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.scss
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json
Labels: testing complete

#3151 SF-3315 Use TranslationScriptureRanges for draft generation
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts
Labels: testing complete

#3147 SF-3198 Fix memory leak in RealtimeService from CheckIfRunning()
  src/SIL.XForge.Scripture/Services/IMachineApiService.cs
  src/SIL.XForge.Scripture/Services/IMachineProjectService.cs
  src/SIL.XForge.Scripture/Services/IParatextSyncRunner.cs
  src/SIL.XForge.Scripture/Services/MachineApiService.cs
  src/SIL.XForge.Scripture/Services/MachineProjectService.cs
  src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  src/SIL.XForge.Scripture/Services/SFServiceCollectionExtensions.cs
  src/SIL.XForge.Scripture/Services/SyncService.cs
  src/SIL.XForge.Scripture/Startup.cs
  src/SIL.XForge.Scripture/packages.lock.json
  src/SIL.XForge/Realtime/IRealtimeService.cs
  src/SIL.XForge/Realtime/MemoryRealtimeService.cs
  src/SIL.XForge/Realtime/RealtimeService.cs
  src/SIL.XForge/SIL.XForge.csproj
  src/SIL.XForge/packages.lock.json
Labels: testing not required

#3155 SF-3318 Skip prompt when no changes made on draft source page
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json
Labels: testing complete

#3168 SF-3301 Use generic logo for white label site
  src/SIL.XForge.Scripture/ClientApp/src/assets/images/sd.svg
  src/SIL.XForge.Scripture/Pages/Shared/_Layout.cshtml
Labels: testing not required

#3169 Fix border radius on draft sources stepper
  src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-sources/draft-sources.component.scss
Labels: testing not required

#3171 Install NPM dependencies ahead of C# CodeQL autobuild
  .github/workflows/codeql.yml
Labels: testing not required

#3176 Fix docker compose build and correct the .dockerignore location
  .dockerignore
  src/SIL.XForge.Scripture/Dockerfile
Labels: testing not required

#3178 Add test analytics reporting to codecov
  .github/workflows/build-and-test.yml
  .gitignore
  src/RealtimeServer/package-lock.json
  src/RealtimeServer/package.json
  src/SIL.XForge.Scripture/ClientApp/package-lock.json
  src/SIL.XForge.Scripture/ClientApp/package.json
  src/SIL.XForge.Scripture/ClientApp/src/karma.conf.js
  test/SIL.Converters.Usj.Tests/SIL.Converters.Usj.Tests.csproj
  test/SIL.XForge.Scripture.Tests/SIL.XForge.Scripture.Tests.csproj
  test/SIL.XForge.Tests/SIL.XForge.Tests.csproj
Labels: testing not required

#3175 SF-3333 Reduce calls to the DBL when configuring sources
  src/SIL.XForge.Scripture/Services/IParatextService.cs
  src/SIL.XForge.Scripture/Services/ParatextService.cs
  src/SIL.XForge.Scripture/Services/SFProjectService.cs
  test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs
Labels: ready to test

#3181 Add a 5 minute timeout for HTTP requests to Serval
  src/SIL.XForge.Scripture/Services/MachineServiceCollectionExtensions.cs
Labels: testing not required

#3159 SF-3298 Save recording automatically (except for inline recording)
  src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts
  src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.stories.ts
Labels: testing complete

#3172 dev: add copilot-instructions.md
  .github/copilot-instructions.md
Labels: testing not required
